### PR TITLE
Core Improvements and Bugfixes

### PR DESCRIPTION
**Pull request by SmartArray**
## Core Improvements and Bugfixes

This PR fixes several bugs that were detected by fixing the functional tests. Those fixes include for instance
- Dandelion bugfixes (mempool bugs)
- RPC bugfixes (`generatetoaddress`, `difficulties`)
- Fee improvements
- Introduction of `easypow` parameter for RegTest
- Several refactorings
- Fixed testnet issues
- Bumped protocol versions
- Proper handling of `WTXID` protocol command

### CODE REVIEW

**Review by JaredTate — APPROVED** [review]
ACK. Awesome work @SmartArray! This seems to finally have eliminated the crash bug with dandelion. Going commit by commit it all looks good. The client compiles, runs, and works as expected. One question I had was the commit about DEFAULT_MIN_RELAY_TX_FEE = 100000. Thats 1/100 of a DGB. Should we make it 1/10?

**Review by gto90 — APPROVED** [review]
ACK

Excellent work on this @SmartArray !  It is absolutely refreshing to be so much closer to having the functional test suite fully operational.  I'm looking forward to review #90 !

**Comment by barrystyle** [comment]
So it was this legacy code that was causing a transaction to effectively be removed twice?
https://github.com/DigiByte-Core/digibyte/pull/89/commits/9be9458db050d036fac286e8fe63c9b32e0a10ea

However this identical code appears in the 0.17 branch as well:
https://github.com/DigiByte-Core/digibyte/blob/develop/src/txmempool.cpp#L526-L530

**Comment by barrystyle** [comment]
image

Receive this on feature/8.22.0 with pull request #89 applied (note that digibyted itself is fine).

**Comment by barrystyle** [comment]
> image
> 
> Receive this on feature/8.22.0 with pull request #89 applied (note that digibyted itself is fine).

If you remove the additional primitives/block.cpp added to the Makefile.am:

```
diff --git a/src/Makefile.am b/src/Makefile.am
index 9ba20eadcc..42f90ee164 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -668,6 +668,7 @@ libdigibyte_cli_a_SOURCES = \
   compat/stdin.h \
   compat/stdin.cpp \
   rpc/client.cpp \
+  primitives/block.cpp \
   $(DIGIBYTE_CORE_H)
   ```
   
and instead make this change to Makefile.am:

```
diff --git a/src/Makefile.am b/src/Makefile.am
index 9ba20eadc..40573435c 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -724,6 +724,8 @@ endif
 digibyte_cli_LDADD = \
   $(LIBDIGIBYTE_CLI) \
   $(LIBUNIVALUE) \
+  $(LIBDIGIBYTE_COMMON) \
+  $(LIBDIGIBYTE_CONSENSUS) \
   $(LIBDIGIBYTE_UTIL) \
   $(LIBDIGIBYTE_CRYPTO)
```

It will compile correctly with no symbol errors.

**Comment by barrystyle** [comment]
Upon running unit tests:

```
root@loderunner:~/digibyte/src/test# ./test_digibyte 
Running 470 test cases...
test_digibyte: test/util/setup_common.cpp:226: TestChain100Setup::TestChain100Setup(): Assertion `m_node.chainman->ActiveChain().Tip()->GetBlockHash().ToString() == "1b14e04a06ce040bf88b9de8f4c2c4bb38c125acefcbdc2fc841d18bb02cdff6"' failed.
unknown location(0): fatal error: in "blockfilter_index_tests/blockfilter_index_initial_sync": signal: SIGABRT (application abort requested)
test/blockfilter_index_tests.cpp(105): last checkpoint: "blockfilter_index_initial_sync" fixture ctor
test_digibyte: util/system.cpp:654: void ArgsManager::AddArg(const string&, const string&, unsigned int, const OptionsCategory&): Assertion `ret.second' failed.
```

**Comment by SmartArray** [comment]
Thank you @barrystyle for testing this.

Yes, I think this is the correct way to deal with the linking error.

There were several issues regarding the mempool. And yes, the code you highlighted was absolutely in there before. That would explain why reorgs caused the client to misbehaving on occasion.

Again, thank you for checking this 🙂

I will apply and check the fix soon!

**Comment by SmartArray** [comment]
> Upon running unit tests:
> 
> 
> 
> ```
> 
> root@loderunner:~/digibyte/src/test# ./test_digibyte 
> 
> Running 470 test cases...
> 
> test_digibyte: test/util/setup_common.cpp:226: TestChain100Setup::TestChain100Setup(): Assertion `m_node.chainman->ActiveChain().Tip()->GetBlockHash().ToString() == "1b14e04a06ce040bf88b9de8f4c2c4bb38c125acefcbdc2fc841d18bb02cdff6"' failed.
> 
> unknown location(0): fatal error: in "blockfilter_index_tests/blockfilter_index_initial_sync": signal: SIGABRT (application abort requested)
> 
> test/blockfilter_index_tests.cpp(105): last checkpoint: "blockfilter_index_initial_sync" fixture ctor
> 
> test_digibyte: util/system.cpp:654: void ArgsManager::AddArg(const string&, const string&, unsigned int, const OptionsCategory&): Assertion `ret.second' failed.
> 
> ```

Found that too. This is because I had to change some network params

**Comment by SmartArray** [comment]
Hey guys, please try to `./autogen.sh`, `./configure` and `make` once more! I have integrated the change as proposed by @barrystyle

**Review by barrystyle — APPROVED** [review]
ACK Happy with these changes

**Comment by ycagel** [comment]
@barrystyle Thanks for the review. Are you able to do PR 90?

**Comment by gto90** [comment]
Very strong work @SmartArray !  Thank you for all your hard effort here.

**Comment by barrystyle** [comment]
> @barrystyle Thanks for the review. Are you able to do PR 90?

can do.

**Pull request merged**
