### PR TITLE
include headers: stdexcept && cstdint

### PR DESCRIPTION
**Pull request by ghost**
Missing headers? #include stdexcept && #include cstdint

**#Chatgpt: Lockedpool.cpp**
---------------------
To use std::runtime_error in C++, you'll need to include the **stdexcept** header. This header provides the standard exception class std::runtime_error 

**#Chatgpt: bip32.h && string.h**
---------------------
The array header provides the functionality for the std::array container, which is a fixed-size array-like structure with some additional features compared to C-style arrays. The **cstdint** header includes definitions for fixed-size integer types, and uint8_t specifically refers to an unsigned 8-bit integer type.

---------------------

**#Bitcoin files**
https://github.com/bitcoin/bitcoin/blob/master/src/support/lockedpool.cpp
Line 23: **#include stdexcept**

https://github.com/bitcoin/bitcoin/blob/master/src/util/bip32.h
line 8: **#include cstdint**

https://github.com/bitcoin/bitcoin/blob/master/src/util/string.h
Line 11: **#include cstdint**

### CODE REVIEW

**Review by chopperbriano — COMMENTED** [review]
Adding includes

**Review by gto90 — APPROVED** [review]
cACK

**Review by j50ng — APPROVED** [review]
cACK

For reference:

https://en.cppreference.com/w/cpp/header/cstdint
https://en.cppreference.com/w/cpp/header/stdexcept

**Comment by ycagel** [comment]
Why is this being added? What exactly is this fixing @Jongjan88?

**Comment by ghost** [comment]
> Why is this being added? 

I added it because I'm 100% sure they're missing.

> What exactly is this fixing @Jongjan88?

ChatGPT:
**Undefined Behavior:** Without the required header, your code might still compile, but it could exhibit undefined behavior. This means that the program might run unpredictably, leading to crashes, incorrect outputs, or other unexpected results.

**Portability Issues:** Code that compiles on one system or with one compiler despite missing headers might fail to compile on a different system or with a different compiler. This lack of portability can cause complications when trying to share or deploy code across various environments.

**Comment by JohnnyLawDGB** [comment]
Necessary to access specific functionalities within C++ that can help with both error correction and portability.

**Review by JaredTate — APPROVED** [review]
ACK. It compiles, builds and runs for me. I see no harm in adding more headers. My question is was there a specific build issue this was solving? Or client behavior its fixing?

**Comment by ghost** [comment]
> ACK. It compiles, builds and runs for me. I see no harm in adding more headers. My question is was there a specific build issue this was solving? Or client behavior its fixing? 

Yes build errors on Ubuntu 23.10.1.

image

**Comment by JaredTate** [comment]
ACK.

> > ACK. It compiles, builds and runs for me. I see no harm in adding more headers. My question is was there a specific build issue this was solving? Or client behavior its fixing?
> 
> Yes build errors on Ubuntu 23.10.1.
> 
> image

Awesome! Thanks for this

**Pull request merged**
