### PR TITLE
Fix GUIX Build For Windows, Linux, Intel Mac

### PR DESCRIPTION
**Pull request by JaredTate**
This PR partially reverts PR https://github.com/DigiByte-Core/digibyte/pull/194 which fixed Apple silicon builds. When I previously tested the GUIX build process for that PR, I only GUIX built Apple silicon and did not realize the changes had broken all the other GUIX builds including Windows, Linux, and Intel Mac builds.

This PR allows us to GUIX build Windows, 3 Linux distros, and Intel Mac, but it breaks the GUIX Apple silicon build. However, it still does build everything & should allow for compiling m1 builds locally. The broken part is in devtools which is needed after the build is complete for GUIX. It would be great to have someone test compile apple silicone from this PR locally to confirm.

In the interest of time getting an RC4 release out, and the recent GoFetch disclosure on vulnerabilities with m1 chips and theft of crypto private keys I am proposing this fix as is for the time being until we can finalize an Apple silicone fix for devtools on GUIX.  I already spent 2.5 days trying to get Apple Silicon to GUIX build along with all the others, but in the interest of time let's get the rest of the RC4 builds out without Apple silicon GUIX. People should still be able to build Apple Silicon locally for their m1 chips if they want.

Screenshot 2024-04-01 at 1 56 34 PM

GUIX Build
```
env HOSTS='x86_64-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu x86_64-w64-mingw32 x86_64-apple-darwin' ./contrib/guix/guix-build
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]
ACK Tested! Nice work @JaredTate . 

Screenshot from 2024-04-01 23-52-50

**Review by ycagel — APPROVED** [review]
cACK. Good job @JaredTate!

**Comment by JaredTate** [comment]
To clarify this PR does successfully compile Apple Silicone on GUIX... it's just the final security check unique to GUIX build process that fails and needs further modifications, which is complicated. ... the actual compilation of the qt is successful so it should build locally for people with m1s.

Screenshot 2024-04-01 at 2 04 24 PM


Full GUIX Security Check Error:

```
 CXXLD    digibyted
  AR       libtest_util.a
  CXXLD    test/test_digibyte
  AR       qt/libdigibyteqt.a
  CXXLD    qt/digibyte-qt
make[2]: Leaving directory '/distsrc-base/distsrc-57a62e3697fe-arm64-apple-darwin/src'
make[1]: Leaving directory '/distsrc-base/distsrc-57a62e3697fe-arm64-apple-darwin/src'
Making all in doc/man
make[1]: Entering directory '/distsrc-base/distsrc-57a62e3697fe-arm64-apple-darwin/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/distsrc-base/distsrc-57a62e3697fe-arm64-apple-darwin/doc/man'
make[1]: Entering directory '/distsrc-base/distsrc-57a62e3697fe-arm64-apple-darwin'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/distsrc-base/distsrc-57a62e3697fe-arm64-apple-darwin'
ld: warning: -no_pie ignored for arm64
F
======================================================================
FAIL: test_MACHO (__main__.TestSecurityChecks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./contrib/devtools/test-security-check.py", line 94, in test_MACHO
    self.assertEqual(call_security_check(cc, source, executable, ['-Wl,-no_pie','-Wl,-flat_namespace','-Wl,-allow_stack_execute','-fno-stack-protector']),
AssertionError: Tuples differ: (1, 'test1: failed NOUNDEFS NX LAZY_BINDINGS Canary CONTROL_FLOW') != (1, 'test1: failed PIE NOUNDEFS NX LAZY_BINDINGS Canary CONTROL_FLOW')

First differing element 1:
'test1: failed NOUNDEFS NX LAZY_BINDINGS Canary CONTROL_FLOW'
'test1: failed PIE NOUNDEFS NX LAZY_BINDINGS Canary CONTROL_FLOW'

- (1, 'test1: failed NOUNDEFS NX LAZY_BINDINGS Canary CONTROL_FLOW')
+ (1, 'test1: failed PIE NOUNDEFS NX LAZY_BINDINGS Canary CONTROL_FLOW')
?                   ++++


----------------------------------------------------------------------
Ran 1 test in 0.515s

FAILED (failures=1)
make: *** [Makefile:1445: test-security-check] Error 1
# ls
```

**Review by gto90 — APPROVED** [review]
ACK

**Pull request merged**
