### PR TITLE
allow selection of correct coinbase maturity value based on height

### PR DESCRIPTION
**Pull request by barrystyle**
782a60737 allow selection of correct coinbase maturity value based on height

### CODE REVIEW

**Comment by Jongjan88** [comment]
Nice work. ty

**Comment by ghost** [comment]
pr155

Pr is working! Now 8.22 connected to the old testnet chain. And mining on it. https://testnetexplorer.digibyteservers.io/ also working.

**Review by gto90 — APPROVED** [review]
Thank you for your contribution and glad to see you back my friend!

cACK

**Comment by saltedlolly** [comment]
Thank you @barrystyle for getting to the bottom of this issue after months of trying to understand it. It's great that the cause has been found before it affected mainnet - a potential disaster has been averted.

Question for the core devs - could we not have a unit test to check for this sort of issue so it does not happen again in future?

Also, I think we should take the RC1 and RC2 binaries down from GitHub given that they have introduced this issue. This will reduce the likelihood of people running them. 

Once this and #154 are merged we are hopefully ready for RC3.

**Comment by beggsdl** [comment]
While this PR addressed a definite issue (thanks @barrystyle), further testing is showing that there are still some things that need to be resolved.

Here are two things I noticed in v8.22 (I tested with the patched version from @Jongjan88, with PR 154 and 157):
1. Coinbase TX will be confirmed after 8 blocks
2. Coinbase TX allowed to be spent before 100 blocks.  TX then gets stuck in mempool.

Core wallet version 7.17.3 handled both of these correctly, not allowing a coinbase tx to be spent before 100 blocks.

I did this testing by solo mining to my core wallet.  Here is a screenshot of the patched v8 wallet confirming a coinbase TX:


Here is that same coinbase TX in the 7.17.3 wallet:


The transaction detail screen in v8 says it needs to mature for 101 blocks before being spent, but you can see in the Status and Credit, that it is only confirming for 9.


This then affects the Immature and Available balances in the v8 wallet (top) compared to the v7 wallet (bottom):


I was then able to try to prematurely spend (before 100 confirmations) some of the coinbase TX from the v8 wallet (the v7 wallet did not allow me to do this due to insufficient funds):



This 50 DGB transaction is now stuck in mempool of the v8 wallet, even 17 hours after being created.

**Comment by saltedlolly** [comment]
Thank you @beggsdl. Excellent detective work!

**Comment by JaredTate** [comment]
Awesome you found this @barrystyle ! Thanks for the contribution. It looks like there might be a couple of other places where `COINBASE_MATURITY_2` needs added properly to fix the issue as @beggsdl mentioned above. 

txmempool.cpp needs an additional `COINBASE_MATURITY_2` entry: https://github.com/DigiByte-Core/digibyte/blob/1c2c6563b6d5e5170cb2fa85a7564657b4d91271/src/txmempool.cpp#L535-L538

Here is txmempool.cpp `COINBASE_MATURITY_2` in 7.17.3:
https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/txmempool.cpp#L522-L529

Also in src/wallet/wallet.cpp looks like we need change to `COINBASE_MATURITY_2` as well: https://github.com/DigiByte-Core/digibyte/blob/1c2c6563b6d5e5170cb2fa85a7564657b4d91271/src/wallet/wallet.cpp#L2904-L2911

Here is what 7.17.3 shows: https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/wallet/wallet.cpp#L4419-L4426

V7.17.3 mentions `COINBASE_MATURITY_2` in these locations: 
Screenshot 2024-01-08 at 12 09 48 PM

current 8.22 including this PR onlys shows `COINBASE_MATURITY_2` in 3 places outside of tests:
Screenshot 2024-01-08 at 12 10 57 PM

I can add additions on to this PR @barrystyle or you can modify yours. Just let me know.

**Comment by beggsdl** [comment]
Thanks @JaredTate.  These are the exact changes I was hoping to test, but have been having trouble doing a build and actually seeing the changes when I run the core wallet.

I also noticed this:
image

And here is what I found in tests so far.  They for the most part use COINBASE_MATURITY (8) and COINBASE_MATURITY_ORIGINAL (100):
image

I can add others as I make note of them.

**Comment by ghost** [comment]
@barrystyle @beggsdl @JaredTate Nice work!!
Screenshot from 2024-01-09 21-09-22
Screenshot from 2024-01-09 21-19-40

**Comment by Jongjan88** [comment]
> Thanks @JaredTate. These are the exact changes I was hoping to test, but have been having trouble doing a build and actually seeing the changes when I run the core wallet.
> 
> I also noticed this: image
> 
> And here is what I found in tests so far. They for the most part use COINBASE_MATURITY (8) and COINBASE_MATURITY_ORIGINAL (100): image
> 
> I can add others as I make note of them.

**Digibyte 7.17.3 & Bitcoin 17 ~ 26:** constexpr size_t NUM_BLOCKS{200};
https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/bench/block_assemble.cpp#L90

**Digibyte 8 Dev:** constexpr size_t NUM_BLOCKS{130}
https://github.com/DigiByte-Core/digibyte/blob/1c2c6563b6d5e5170cb2fa85a7564657b4d91271/src/bench/block_assemble.cpp#L27

@JaredTate

**Comment by saltedlolly** [comment]
Given that we have a lot of other fixes waiting on this one, I suggest we merge this as is. PRs for the remaining fixes can be made separately. Thank you again @barrystyle for identifying the issue. I am going to approve.

**Review by saltedlolly — APPROVED** [review]
utACK

**Comment by ghost** [comment]
**txmempool.cpp**https://github.com/DigiByte-Core/digibyte/commit/a253bed796e94ddadf7a9a24e4419e71538ac322

https://github.com/DigiByte-Core/digibyte/blob/a253bed796e94ddadf7a9a24e4419e71538ac322/src/txmempool.cpp#L536-L546

**wallet/wallet.cpp**https://github.com/DigiByte-Core/digibyte/commit/f35de134a6858857b08de58e00ec8d3f7a01f64c

https://github.com/DigiByte-Core/digibyte/blob/f35de134a6858857b08de58e00ec8d3f7a01f64c/src/wallet/wallet.cpp#L2910

Can we Merge this PR? Or first add this and then merge?

**Comment by ycagel** [comment]
Has there been sufficient testing on this PR before considering merging?

**Comment by beggsdl** [comment]
> Has there been sufficient testing on this PR before considering merging?

Several of us have been running it since the fix was made.  It did fix the issue of v8 going onto the longer chain with prematurely spend coins in one of the transactions.  Without the txmempool.cpp and wallet.cpp fixes though, you can still attempt to prematurely spend coins from a coinbase transaction.  That new tx then gets stuck in mempool.  If possible, it would be nice to have these two fixes included so we can officially test all the COINBASE_MATURITY_2 fixes at the same time.  COINBASE_MATURITY is also used in src/bench/block_assemble.cpp, but I am not sure if it really needs to be changed there or not.

**Comment by ghost** [comment]
> Has there been sufficient testing on this PR before considering merging?

Yes we tested it a lot. The pr is 100% working. And used by all v8 testnet nodes.

**Comment by Jongjan88** [comment]
> COINBASE_MATURITY is also used in src/bench/block_assemble.cpp, but I am not sure if it really needs to be changed there or not.

block_assemble.cpp COINBASE_MATURITY in dgb 8 dev is the same as 7.17.3.

**Digibyte 7.17.3**
https://github.com/DigiByte-Core/digibyte/blob/release/v7.17.3/src/bench/block_assemble.cpp#L97

https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/bench/block_assemble.cpp#L91

https://github.com/DigiByte-Core/digibyte/blob/258afaceba07a16b8cf3acefc5bf2ce70d213b68/src/bench/block_assemble.cpp#L97

**Review by ycagel — APPROVED** [review]
cACK.

**Review by j50ng — APPROVED** [review]
cACK

**Comment by ycagel** [comment]
Please reference the following issue:

https://github.com/DigiByte-Core/digibyte/issues/161

The work to resolve that issue will be done in another PR.

**Pull request merged**
