### PR TITLE
chainparams, tests: Fix Taproot activation and wallet_taproot.py functional test

### PR DESCRIPTION
**Pull request by gto90**
This pull request addresses the following changes to ensure the functionality of the wallet_taproot.py test:

- **chainparams.cpp**:
  - Updated Taproot deployment parameters in `CRegTestParams` class to ensure accurate activation times and conditions.
  - Adjusted other consensus parameters to align with the changes required for Taproot activation.

- **wallet_taproot.py**:
  - Modified the test setup to correctly initialize Taproot activation parameters.
  - Enhanced the test logic to ensure that Taproot-related descriptors are accurately imported and validated.

These changes ensure that the Taproot functionality is correctly activated and tested in the DigiByte Core environment.

### Motivation

The modifications are necessary to fix the `wallet_taproot.py` functional test, which ensures the correct generation and spending of P2TR (Pay-to-Taproot) addresses.

### Testing

- Ran the `wallet_taproot.py` functional test suite and confirmed that all tests pass successfully.
- Verified that Taproot-related descriptors are correctly handled in activated and non-activated scenarios.

### Additional Notes

- No changes to the documentation or other test suites are required as part of this update.

### CODE REVIEW

**Review by JaredTate — APPROVED** [review]
ACK! Great work @gto90. Changes look clean, wallet compiles, runs, and when I boot into regtest mode I get the correct response for taproot activation from getblockchaininfo. 

Now for fixing final python test, and then we should probably run through a taproot activation process on testnet, or at least a local modified testnet.

I will then need to add a page to the stats site to track activation process.

Screenshot 2024-12-18 at 8 20 32 AM

Screenshot 2024-12-18 at 9 16 35 AM

**Comment by beggsdl** [comment]
@JaredTate  I am still mining Testnet, so let me know if you need me to do anything for this.

**Review by ycagel — APPROVED** [review]
cACK.

**Comment by JaredTate** [comment]
> @JaredTate I am still mining Testnet, so let me know if you need me to do anything for this.

Thank you for continuing to support Testnet! I am thinking its time we reset it with a final 8.22 release. I will look into that and work on a PR for it. We can also put it up on DigiHash.

**Pull request merged**
