### PR TITLE
This PR introduces support for GUIX cross compilations

### PR DESCRIPTION
**Pull request by SmartArray**
# GUIX Support

After a few brutal days, I finally got the GUIX cross compilation working. It will produce binaries for the following architectures:

- `arm-linux-gnueabihf`
- `aarch64-linux-gnu`
- `riscv64-linux-gnu`
- `powerpc64-linux-gnu`
- `powerpc64le-linux-gnu`
- `x86_64-w64-mingw32`
- `x86_64-apple-darwin18`

### Ubuntu
On Debian/Ubuntu you can use `apt install guix` to install `guix` and run `./contrib/guix/guix-build`.
For detailed instructions, refer to the docs https://github.com/DigiByte-Core/digibyte/tree/develop/contrib/guix.

### MacOS/Windows
For Mac OS and Windows you can use `docker` and these instructions to run the GUIX build.
https://github.com/DigiByte-Core/DigiByte-GUIX-Docker/tree/main

### CODE REVIEW

**Comment by SmartArray** [comment]
A good side effect of this PR is that it fixes all the CI checks too 🎉

**Review by j50ng — APPROVED** [review]
ACK- tested build successfully.  Approx ~4hrs w/ Ubuntu on Intel Core i7-6700K @ 4.00GHz - 4 cores 16Gb ram.  Will test w/ Docker on Ubuntu next.  Great work @SmartArray!

**Review by JaredTate — APPROVED** [review]
tACK. The Guix process works great for me if I build one architecture at a time. It tends to timeout on some downloads if I try to build all at once. Thanks Yoshi! Great work

**Review by gto90 — APPROVED** [review]
tACK

Great job on this @SmartArray !  I am approving this PR while also raising the following [GitHub Issue](https://github.com/DigiByte-Core/digibyte/issues/111) to resolve the issues building for Apple Silicon.  I think it is appropriate for a release candidate but the aforementioned issue should be resolved prior to a general release.

**Pull request merged**
