### PR TITLE
Fixed remaining Functional tests for 8.22

### PR DESCRIPTION
**Pull request by SmartArray**
This PR fixes the remaining functional tests.

It fixes the invalid mempool notification behaviour caused by Dandelion, which was basically announcing TXs twice.
Also fixed a few minor by adapting them to the new boost-API or disabling IPv6 tests (that will be working in 8.23)

### CODE REVIEW

**Comment by saltedlolly** [comment]
Yoshi, you legend! 👏

**Comment by SmartArray** [comment]
Cherry picked commits `5e337561d897a40750b1de104a74f102f8e38a1f ` and `8d4403950bc9c4a691dbdbc04cf4de2600e51f3b ` from Bitcoin upstream to replace the `ripemd160` used in the functional tests with a pure-python implementation because some OpenSSL installations disabled this very specific algorithm.

No modifications in your OpenSSL installation needed with these fixes.

**Comment by JaredTate** [comment]
Bitcoin Core completely ripped out OpenSSL tests as OpenSSL3 changed a ton of stuff and broke many things in core tests. Just pushed a change to get tests passing and disable the broken SSL tests. To date OpenSSL tests are not back in BTC core v22 or 23.

Added the following to configure.ac

`--disable-openssl-tests"`

Look here for BTC devs rationale for removing OpenSSL tests: https://github.com/bitcoin-core/secp256k1/pull/983

**Review by gto90 — APPROVED** [review]
ACK

Thank you for this hard work @SmartArray !

I have tested this on MacOS 13.2 with an M1 CPU as well as Ubuntu Linux 22.10.  All unit tests pass as well as all functional tests.

**Review by JaredTate — APPROVED** [review]
ACK. Thank you Yoshi and everyone for your work on this!

**Pull request merged**
