### PR TITLE
Add Jared Tate GPG Key

### PR DESCRIPTION
**Pull request by JaredTate**
This is my GPG key for releasing signing. For time being I suggest we leave all the BTC dev keys in case they ever decided to help DGB more directly. If you want to help sign the next 8.22 release please add your GPG key to the top of this list above mine.

### CODE REVIEW

**Review by ycagel — APPROVED** [review]
ACK

**Review by j50ng — APPROVED** [review]
ACK

**Review by SmartArray — APPROVED** [review]
ACK

**Review by gto90 — APPROVED** [review]
ACK

**Pull request merged**
