### PR TITLE
Dandelion removal

### PR DESCRIPTION
**Pull request by barrystyle**
Remove dandelion for debugging/refactoring; includes code added for tests.

### CODE REVIEW

**Comment by JaredTate** [comment]
Thanks for doing this Barry. Definitely makes sense for us to start a new Dandelion Feature 8.22 branch by itself. Would be great to get 8.22 merged into develop as well.

**Comment by JaredTate** [comment]
ACK. Client compiles & runs fine. Lets get dandelion in its own feature branch, and I am all for getting 8.22 merged into develop. Lets start feature branches for all the things we want to add in.

**Comment by JaredTate** [comment]
Created https://github.com/DigiByte-Core/digibyte/tree/feature/8.22dandelion

**Review by gto90 — APPROVED** [review]
ACK

Thank you for this @barrystyle .  We're looking forward to picking the reimplementation of Dandelion back up on the new feature branch as a focused effort.

**Review by JaredTate — APPROVED** [review]
Double ACK

**Pull request merged**
