### PR TITLE
Update chainparams.cpp

### PR DESCRIPTION
**Pull request by bastiandriessen**
New seed servers:
MAINNET ( Sydney, Australia ): seed.digibyte.link ( 103.230.158.91 ) &&
testnet ( Brisbane, Australia ): testnetseed.digibyte.link ( 175.45.182.173 )

Bastian Driessen

### CODE REVIEW

**Review by saltedlolly — DISMISSED** [review]
tACK

Tested:
https://www.whatsmydns.net/#A/seed.digibyte.link
https://www.whatsmydns.net/#A/testnetseed.digibyte.link

Many thanks for running these!

**Comment by ycagel** [comment]
Is this the correct file that needs to be modified?

**Review by j50ng — DISMISSED** [review]
tACK- thanks Bastian!

**Review by SmartArray — DISMISSED** [review]
tACK

**Review by ycagel — DISMISSED** [review]
tACK - Thank you!

**Review by JaredTate — APPROVED** [review]
tACK

**Review by ycagel — APPROVED** [review]
tACK - Great job!

**Review by j50ng — APPROVED** [review]
tACK

**Review by gto90 — APPROVED** [review]
cACK

**Pull request merged**
