### PR TITLE
Policy

### PR DESCRIPTION
**Pull request by ghost**
Update src/policy/
**Before** 
`GetFee(1000)` 
**After** 
`GetFee(100000)`

---------------------------------------------------
**Before** 
```
MIN_BUCKET_FEERATE = 1000
MIN_BUCKET_FEERATE = 1e7
```
**After** 
```
MIN_BUCKET_FEERATE = 1e7
MIN_BUCKET_FEERATE = 1e10
```

---------------------------------------------------
**Before** 
`MAX_FILTER_FEERATE = 1e7`
**After** 
`MAX_FILTER_FEERATE = 1e10`

### CODE REVIEW

**Comment by ghost** [comment]
After Pr174 and updates in addrman_tests.cpp
[src/test/addrman_tests.cpp](https://github.com/Jongjan88/digibyte/commit/f4bf02375f0333db85b8fc7423d230fa62b3432f#diff-34d1a0e093152df355fc3a6b5b06156f7a9b936bfffb26bb221e62828e44532f)

Screenshot from 2024-02-21 01-28-23

**Review by JaredTate — APPROVED** [review]
ACK. Compiles & runs great.  TX's send without issue. Thanks for this!

**Review by gto90 — APPROVED** [review]
utACK

Excellent work here @Jongjan88, thank you for this contribution!

**Review by ycagel — APPROVED** [review]
cACK. Thanks @Jongjan88!

**Pull request merged**
