### PR TITLE
small wording changes

### PR DESCRIPTION
**Pull request by mctrivia**
adjusted wording for clarity and to remove telegram and mailing list.

### CODE REVIEW

**Comment by ChillingSilence** [comment]
ACK, good clarification, thanks @mctrivia

**Comment by ycagel** [comment]
ACK, good find @mctrivia

**Review by ycagel — APPROVED** [review]

**Review by gto90 — APPROVED** [review]
cACK

Thanks for the contribution!

**Comment by ycagel** [comment]
Josiah, can you approve the changes? This way we can merge the request.

**Review by ChillingSilence — APPROVED** [review]
Apologies I'd written it in the comments above, but not hit the magic button.

**Review by gto90 — APPROVED** [review]
cACK

**Pull request merged**
