### PR TITLE
Added DigiByte Logo in markdown README

### PR DESCRIPTION
**Pull request by SmartArray**
## Added DigiByte Logo in README

Latest chrome will even change the font color, depending on what system theme is active.
Support for Safari/Brave should be added soon.

### Other fixes
README badge/shield fixed

### CODE REVIEW

**Comment by ChillingSilence** [comment]
ACK  looks good thanks Yoshi!! :-)

**Review by gto90 — APPROVED** [review]
ACK

**Review by digicontributer — APPROVED** [review]
ACK

**Review by JaredTate — COMMENTED** [review]
ACK

**Pull request merged**
