### PR TITLE
This PR fixes 5 functional tests.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes 5 functional tests.

To test this:

Compile:

  ./autogen.sh
  ./configure
  make -j 8

Run Specific Functional Tests

```
python wallet_send.py --descriptors 
python wallet_send.py --legacy-wallet
python rpc_net.py
python wallet_balance.py --descriptors
python wallet_balance.py --legacy-wallet
```

### CODE REVIEW

**Comment by JaredTate** [comment]
Awesome! Wallet compiles & runs well, but 1 of the 5 tests still fails for me.   wallet_balance.py --legacy-wallet failed,

Screenshot 2024-03-07 at 6 38 49 PM

**Comment by JaredTate** [comment]
Never mind, rerunning wallet_balance.py --legacy-wallet again and it works. I've noticed a lot of tests intermittently fail and need to be re-run. 

Screenshot 2024-03-07 at 6 41 56 PM

**Review by JaredTate — APPROVED** [review]
ACK. Great work! Straight forward changes.

**Comment by JaredTate** [comment]
FYI you can run multiple tests by daisy chaining them for a custom test:

Example:
`test/functional/test_runner.py wallet_send.py rpc_net.py wallet_balance.py`

**Comment by beggsdl** [comment]
Great job guys.  It is great to see so many of the tests being addressed.

**Review by ycagel — APPROVED** [review]
cACK. Good work @Jongjan88!

**Review by gto90 — APPROVED** [review]
utACK

**Pull request merged**
