### PR TITLE
DigiByte Core ( BTC22.1 Backports for BTC Core 22  )

### PR DESCRIPTION
**Pull request by ghost**
Fixes Included:
[build: Restrict check for CRC32C intrinsic to aarch64 #23045](https://github.com/bitcoin/bitcoin/pull/23045)
[Fix (inverse) meaning of -persistmempool #23061](https://github.com/bitcoin/bitcoin/pull/23061)
[build: Fix guix linker-loader path and add check_ELF_interpreter #23148](https://github.com/bitcoin/bitcoin/pull/23148)
[system: skip trying to set the locale on NetBSD #22390](https://github.com/bitcoin/bitcoin/pull/22390)
[build, qt: Fix typo in QtInputSupport check #22820](https://github.com/bitcoin/bitcoin/pull/22820)
[wallet: fix the behavior of IsHDEnabled, return false in case of a blank hd wallet. #22781](https://github.com/bitcoin/bitcoin/pull/22781)
[consensus: don't call GetBlockPos in ReadBlockFromDisk without cs_main lock #22895](https://github.com/bitcoin/bitcoin/pull/22895)
[refactor: include a missing <limits> header in fs.cpp #23335](https://github.com/bitcoin/bitcoin/pull/23335)
[wallet: fix segfault by avoiding invalid default-ctored external_spk_managers entry #23333](https://github.com/bitcoin/bitcoin/pull/23333)
[build: patch qt to explicitly define previously implicit header include  #23580](https://github.com/bitcoin/bitcoin/pull/23580)
[ci: Replace soon EOL hirsute with jammy #23504](https://github.com/bitcoin/bitcoin/pull/23504)
[test: fix ceildiv division by using integers #24239](https://github.com/bitcoin/bitcoin/pull/24239)

Screenshot from 2024-04-10 12-02-15

Screenshot from 2024-04-10 12-39-14

### CODE REVIEW

**Comment by JaredTate** [comment]
So this PR compiles, runs, and all tests pass. But when looking at all was exactly changed you reference:
[build: patch qt to explicitly define previously implicit header include  #23580](https://github.com/bitcoin/bitcoin/pull/23580)

But those changes are not in this PR? Were they already changed?

Screenshot 2024-04-13 at 7 52 36 AM

**Comment by ghost** [comment]
> So this PR compiles, runs, and all tests pass. But when looking at all was exactly changed you reference: [build: patch qt to explicitly define previously implicit header include #23580](https://github.com/bitcoin/bitcoin/pull/23580)
> 
> But those changes are not in this PR? Were they already changed?
> 
> Screenshot 2024-04-13 at 7 52 36 AM

Yes parts where already in it. After this pr we have all updates/fix from btc core 22.1. In DigiByte core.

**Comment by JaredTate** [comment]
> Yes parts where already in it. After this pr we have all updates/fix from btc core 22.1. In DigiByte core.

Awesome, good stuff. The rest look straightforward and helpful. I am waiting for all the Python functional tests to run and will ACK it.

**Review by gto90 — APPROVED** [review]
utACK

**Review by JaredTate — APPROVED** [review]
ACK! Good work @Jongjan88 All python functional tests pass too. 
Screenshot 2024-04-13 at 9 36 17 AM

**Review by ycagel — APPROVED** [review]
cACK.

**Pull request merged**
