### PR TITLE
Docs: Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by gto90**
This pull request updates the CONTRIBUTING.md file to follow MD formatting guidelines and strict linting rules.

Additionally, this pull request updates the `Contributor Workflow` section which adds GitFlow as the official branching methodology and developer workflow.

Finally, better formatted and organized language describing the pull request philosophy, peer review process and merging process.

**Reviewer Note**: Upon successful review, this pull request should retarget the develop branch.

### CODE REVIEW

**Comment by ChillingSilence** [comment]
ACK
Thanks for your input @gto90 . This is great and I'm looking forward to this process for DigiByte!

Perhaps it's also worth clarifying contributions from prospective reviewers, it mentions over time having people becoming more "known" but for other highly competent coders who would like to contribute, was the only thing I noticed missing, though I'm aware that's kinda nit-picking 😅

**Comment by j50ng** [comment]
cACK
Thank you everyone for being a part of this. Despite the hardest moments you guys always find a way to keep us moving forward.  It's so challenging being part of a grass-roots community of volunteers in a purely decentralized blockchain with little funding.  But, it's so rewarding to see how many people make it a priority to better this technology and the community.  I don't want to just say thank you for all you do.  I hope to make it our mission to build a development environment and community that is worthy of what you guys have put so much into and built.  Thank you Jared for entrusting and empowering those around you to keep building and moving DigiByte forward.  Thank you @ChillingSilence for always educating us so that we ALL can be better equipped and effective in our efforts for DigiByte. Thank you @gto90 for getting this all organized. I truly believe you have put serious and sound methodologies in place that are absolutely essential to mitigate risks and deliver the best so that we don't jeopardize the future of this blockchain. This is exactly what we need. Thank you @DigiContributer and @SmartArray for your endless contributions, bringing us here, and for agreeing to peer review.  You guys have done so much, are busier than ever, and you still give your time for us.  And thank you @barrystyle, for agreeing to start all over even before the beginning- you're a legend for still being here and you have our gratitude. I am excited, thankful, and truly appreciate being a part of this.

**Comment by digicontributer** [comment]
cACK

Can't stop the slow march of progress. Cheers everyone involved.

**Review by digicontributer — APPROVED** [review]
cACK

Can't stop the slow march of progress, Cheers everyone involved in getting us here.

**Pull request merged**
