### PR TITLE
Update chainparams.cpp

### PR DESCRIPTION
**Pull request by cdonnachie**
Seed Node Addition for Mainnet and Testnet

- seed.digibyte.services
- testnetseed.digibyte.services

### CODE REVIEW

**Review by Sbosvk — APPROVED** [review]
utACK

**Comment by Sbosvk** [comment]
tACK most recent commit

**Review by ycagel — APPROVED** [review]
tACK - Thank you!

**Review by saltedlolly — APPROVED** [review]
tACK

Looks good. I'm seeing several results for both. 

Mainnet: https://www.whatsmydns.net/#A/seed.digibyte.services
Testnet: https://www.whatsmydns.net/#A/testnetseed.digibyte.services

**Review by gto90 — APPROVED** [review]
utACK

**Comment by saltedlolly** [comment]
I'm confused how we can have four approvals but still need one more?!

Apparently all approvals are equal, but some approvals are more equal than others. 🐷🤣

**Comment by saltedlolly** [comment]
I think I found the reason: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews 

"If your repository requires approving reviews from people with write or admin permissions, then any approvals from people with these permissions are denoted with a green check mark, and approvals from people without these permissions have a gray check mark. Approvals with a gray check mark do not affect whether the pull request can be merged."

**Review by j50ng — APPROVED** [review]
utACK

💪

**Pull request merged**
