### PR TITLE
Port 8333 to 12024

### PR DESCRIPTION
**Pull request by ghost**
Change port 8333 / 18333 ( Bitcoin ) to 12024 / 12026 ( Digibyte )

digibytiup

### CODE REVIEW

**Review by JaredTate — APPROVED** [review]
cACK, Awesome! Thank you for helping clean this up. This was much needed.

**Review by JaredTate — APPROVED** [review]
cACK. Thanks again. Guess I need to review twice as first didn't count.

**Review by gto90 — APPROVED** [review]
cACK

Thank you very much for your contributions to the 8.22 release.

**Comment by saltedlolly** [comment]
Quick question for @SmartArray @gto90 @JaredTate - when it comes to PRs with smaller fixes/tweaks like this one, is it preferable to make the PR to this 'release/8.22.0-rc2' branch, or better to use the 'develop' branch, or does it not matter?

I already asked this on Gitter but haven't received a response.

**Comment by JaredTate** [comment]
> Quick question for @SmartArray @gto90 @JaredTate - when it comes to PRs with smaller fixes/tweaks like this one, is it preferable to make the PR to this 'release/8.22.0-rc2' branch, or better to use the 'develop' branch, or does it not matter?
> 
> I already asked this on Gitter but haven't received a response.

I would say develop. What does everyone else think? Typically an rc branch is made right before a release with a feature freeze as I understand it in general preactice. Plus I think it's easier to pull and test from develop. Cheers

**Comment by gto90** [comment]
I agree with PRs targeting the develop branch but I overlooked it here because we can merge it back into develop before cutting the next release candidate.

**Review by ycagel — APPROVED** [review]
cACK. Appreciate all your effort @Jongjan88.

**Pull request merged**
