### PR TITLE
Bump Version to 8.22.0-RC4

### PR DESCRIPTION
**Pull request by JaredTate**
It would be great to cut an RC4 release here shortly. I think now that all failing tests have been fixed, Apple Silicon is compiling, and with all the changes we have made it would be a great time to cut a release fixing a lot of problems and get more testers on board. 

I can GUIX build the release and tag it, but I would love to have descriptors as default in an RC4 for more testing. So PR https://github.com/DigiByte-Core/digibyte/pull/213 still needs approved. 

Big thanks to @saltedlolly for thinking ahead with the RC4 graphic in https://github.com/DigiByte-Core/digibyte/pull/170.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by ycagel — APPROVED** [review]
cACK

**Comment by saltedlolly** [comment]
Good plan.

Could we please try and ensure that the file and folder names are consistent this time? It might be good to update GUIX to ensure that the builds follow the file and folder naming conventions discussed here: https://github.com/DigiByte-Core/digibyte/issues/138

Also, I really think it would a good policy to have a few of us build RC4 and generate keys to sign off on it like we did for RC2. We did not do this for RC3. These binaries are easy for non-developers to download, even if they are pre-releases, and I think it would be worth taking the extra steps to have a few of us sign them. (Say at least three people.) People should not have to trust any one developer to compile. If a few of us sign them then they don't have to.

**Review by gto90 — APPROVED** [review]
ACK

**Comment by JaredTate** [comment]
> Good plan.
> 
> Could we please try and ensure that the file and folder names are consistent this time? It might be good to update GUIX to ensure that the builds follow the file and folder naming conventions discussed here: #138
> 
> Also, I really think it would a good policy to have a few of us build RC4 and generate keys to sign off on it like we did for RC2. We did not do this for RC3. These binaries are easy for non-developers to download, even if they are pre-releases, and I think it would be worth taking the extra steps to have a few of us sign them. (Say at least three people.) People should not have to trust any one developer to compile. If a few of us sign them then they don't have to.

I have no problem signing an RC4, but it will take us a lot longer for a release. We definitely need to sign the final 8.22.0 release. The thing is the commit hash is verified when you upload binaries built from the specific tag, so anyone can easily verify the build that way. There is a green checkmark.

As for the file & folder names, the commit hash is required to be in the naming as part of the signing process. So I am not sure what file name/folder structure you are looking for, but it will mess up the actual GUIX signing process by removing commit hashes in file/ folder names.

**Pull request merged**
