### PR TITLE
WIP: Feature/8.22.0

### PR DESCRIPTION
**Pull request by gto90**
**All four GitHub Actions finally ran through 🎉🥳**
### 🔥 _This is a huge milestone for this pull request (PR)_ 🔥

However, the PR is not fully finished yet. We have a bunch of things to test thoroughly and several changes to consensus critical parameters to double check.
Throughout the last weeks, while I was working on this PR, I noted down a bunch of different things that are critical to this release:

- [x] `TODO-001`: Several deployments were moved to buried deployments. New values for the activation block heights were chosen by myself by looking up block heights in the block explorer. Example commit: https://github.com/JaredTate/digibyte/commit/3c7a7d315a8f646ebb887630981b4d5989bcd066
**Required steps:**
  - [x] Validate that chosen block height for `DEPLOYMENT_CSV` and `DEPLOYMENT_NVERSIONBIPS` (~~4164302~~) was chosen correctly
  - [x] Validate that chosen block height for `DEPLOYMENT_SEGWIT` (4394880) was chosen correctly
  - [x] Validate that chosen block height for `DEPLOYMENT_RESERVEALGO` (~~7550000~~) was chosen correctly
  - [x] Perform a full sync and validate that the node syncs to 100% without rejecting any blocks that have new versions active

- [ ] `TODO-002`: Throughout fixing the automated unit tests for Qt we noticed that the current fee model for DigiByte needed special care. The commit https://github.com/JaredTate/digibyte/commit/4c03608a99a9d42e837f2391e39405ca43df2ba4 increases the incremental relay fee for replacement transactions (BIP 125) by 200x that was required for Rbf. This _shouldn't_ have an impact at all since Rbf is disabled for DigiByte currently.
**Required steps:**
  - [ ] Discuss whether Rbf shall remain disabled for the next release. Due to the small block time it is unlikely we will enable Rfb at all.
  - [ ] Create a bunch of transactions using `digibyte-tx` and `digibyte-qt`, validate the calculated fee is still correct and transactions will **not** be rejected by the network

- [x] `TODO-003`: Validate that `digibyte-qt` is working properly.
**Required steps:** 
  - [x] Ensure `digibyte-qt` shows the correct DigiByte network parameters
  - [x] Ensure `digibyte-qt` is not crashing when sending a regular transaction

- [ ] `TODO-004`: The bitcoin upstream changes caused a big refactoring of internal classes, etc. This forced us to reintegrate Dandelion-specific code, which might have broken Dandelion.
  - [ ] Validate Dandelion is really disabled when using `-disable-dandelion` arg and non-dandelion transactions can be crafted and broadcasted
  - [ ] Validate Dandelion is enabled (i.e. dandelion thread is starting) when **not** specifying `-disable-dandelion` arg 
  - [ ] Validate Dandelion is enabled and correctly broadcasting a dandelion transaction (observe logs!!). Ensure that the transaction eventually transitions from the stempool into the real mempool.
  - [ ] Validate Dandelion is enabled but normal transactions are still possible

- [ ] `TODO-005`: Similar to `TODO-004` we need to validate MultiAlgo is working properly
  - [x] A full sync will already show that MultiAlgo is still working, as it would reject blocks if not working properly.
  - [ ] Try to submit malicious blocks and ensure they are properly rejected by the network (wrong high-hash)
  - [ ] Use a real Odocrypt miner to mine a block in testnet. An attempt to mine `N` consecutive blocks should show the adapting difficulty.
  - [ ] Use a real Odocrypt miner to mine a block in mainnet

- [ ] `TODO-006`: During the merge, Taproot (🚀) was introduced into our codebase. The unit tests already validate that taproot is working as expected.
**Required steps:**
  - [x] Alter and validate activation parameters (https://github.com/JaredTate/digibyte/blob/eaeadc657b49d39a71b21cbb1fa9d61a028cff55/src/chainparams.cpp#L157)
  - [ ] Perform testnet sync and ensure that taproot is disabled before reaching the desired block height, and activated after reaching it.

- [ ] `TODO-007`: DigiByte Signet has been added. Validate signet parameters.

- [x] `TODO-008`: Perform a fresh sync in DigiByte Testnet. Ensure that no crashes, no weird warnings and no unexpected behavior occurs.

- [x] `TODO-009`: Perform a fresh sync in DigiByte Mainnet. Ensure that no crashes, no weird warnings and no unexpected behavior occurs. Ensure that the client is not forking.

Not saying this list is complete, but it should serve as a perfect starting point.

When most of the tasks are completed, we could soon start the review and aim at an eventual approval.
From that point, we need to double test everything is working properly, add possibly create release candidates and finally distribute signed releases.

Theoretically, we can work on integrating additional features (sync improvements, new mining algorithms?) before creating an official release.

### CODE REVIEW

**Comment by JaredTate** [comment]
Testing RPC Commands in v 8.22

**Blockchain RPCs**
- [x] getbestblockhash -working
- [x] getblock -working
- [x] getblockchaininfo -working
- [x] getblockcount -working
- [x] getblockfilter -working, needs indexing turned on to test
- [x] getblockhash -working
- [x] getblockheader -working
- [x] getblockstats -working
- [x] getchaintips -working
- [x] getchaintxstats -working
- [x] getdifficulty -working
- [ ] getmempoolancestors - not working, or I am not testing right
- [ ] getmempooldescendants - not working, or I am not testing right
- [x] getmempoolentry -working
- [x] getmempoolinfo -working.... but should it have dandelion info?
- [x] getrawmempool -working
- [x] gettxout -working
- [x] gettxoutproof -working
- [x] gettxoutsetinfo -working
- [ ] preciousblock
- [x] pruneblockchain
- [ ] savemempool
- [ ] scantxoutset
- [x] verifychain -working
- [ ] verifytxoutproof

**Contol RPC's**
- [x] getmemoryinfo -working
- [x] getrpcinfo -working
- [x] help -working
- [x] logging -working
- [x] stop -working
- [x] uptime -working

**Generating RPCs**

- [ ] generateblock
- [ ] generatetoaddress
- [ ] generatetodescriptor

**Mining RPCs**
- [ ] getblocktemplate
- [x] getmininginfo -working
- [ ] getnetworkhashps - not calculating correctly
- [ ] prioritisetransaction
- [ ] submitblock
- [ ] submitheader


**Network RPC's**
- [x] addnode -working
- [x] clearbanned -working
- [x] disconnectnode -working
- [x] getaddednodeinfo -working
- [x] getconnectioncount -working
- [x] getnettotals -working
- [x] getnetworkinfo -working
- [x] getnodeaddresses -working
- [x] getpeerinfo -working
- [x] listbanned -working
- [x] ping -working
- [x] setban -working
- [x] setnetworkactive -working

**Comment by JaredTate** [comment]
**Rawtransactions RPCs**

- [ ] analyzepsbt
- [ ] combinepsbt
- [ ] combinerawtransaction
- [ ] converttopsbt
- [ ] createpsbt
- [ ] createrawtransaction
- [ ] decodepsbt
- [ ] decoderawtransaction
- [ ] decodescript
- [ ] finalizepsbt
- [ ] fundrawtransaction
- [ ] getrawtransaction
- [ ] joinpsbts
- [ ] sendrawtransaction
- [ ] signrawtransactionwithkey
- [ ] testmempoolaccept
- [ ] utxoupdatepsbt

**Util RPCs**

- [ ] createmultisig
- [ ] deriveaddresses
- [x] estimatesmartfee -working
- [x] getdescriptorinfo
- [ ] getindexinfo
- [ ] signmessagewithprivkey
- [x] validateaddress -working
- [ ] verifymessage

**Comment by JaredTate** [comment]
**Wallet RPCs**
Note: the wallet RPCs are only available if DigiByte Core was built with wallet support, which is the default.

- [x] abandontransaction
- [x] abortrescan
- [ ] addmultisigaddress
- [x] backupwallet
- [ ] bumpfee
- [x] createwallet -working
- [ ] dumpprivkey
- [ ] dumpwallet
- [x] encryptwallet
- [x] getaddressesbylabel
- [x] getaddressinfo -working
- [x] getbalance -working
- [x] getbalances -working
- [x] getnewaddress -working
- [x] getrawchangeaddress -working
- [x] getreceivedbyaddress -working
- [x] getreceivedbylabel -working
- [x] gettransaction -working
- [x] getunconfirmedbalance -working
- [x] getwalletinfo -working
- [ ] importaddress
- [ ] importdescriptors
- [ ] importmulti
- [ ] importprivkey
- [ ] importprunedfunds
- [ ] importpubkey
- [ ] importwallet
- [ ] keypoolrefill
- [x] listaddressgroupings -working
- [x] listlabels -working
- [x] listlockunspent
- [x] listreceivedbyaddress -working
- [x] listreceivedbylabel -working
- [x] listsinceblock -working
- [x] listtransactions -working
- [x] listunspent -working
- [x] listwalletdir -working
- [x] listwallets -working
- [ ] loadwallet
- [ ] lockunspent
- [ ] psbtbumpfee
- [ ] removeprunedfunds
- [ ] rescanblockchain
- [ ] send
- [ ] sendmany
- [ ] sendtoaddress
- [ ] sethdseed
- [ ] setlabel
- [ ] settxfee
- [ ] setwalletflag
- [ ] signmessage
- [ ] signrawtransactionwithwallet
- [ ] unloadwallet
- [ ] upgradewallet
- [ ] walletcreatefundedpsbt
- [ ] walletlock
- [ ] walletpassphrase
- [ ] walletpassphrasechange
- [ ] walletprocesspsbt

**Comment by SmartArray** [comment]
## TODO-001
I finally found some time to validate the block heights for all buried deployments. This is what I came up with:

| DEPLOYMENT NAME         | DEPLOYMENT HEIGHT |
|-------------------------|-------------------|
| DEPLOYMENT_CLTV         | 4394880           |
| DEPLOYMENT_DERSIG       | 4394880           |
| DEPLOYMENT_CSV          | 4394880           |
| DEPLOYMENT_SEGWIT       | 4394880           |
| DEPLOYMENT_NVERSIONBIPS | 4394880           |
| DEPLOYMENT_RESERVEALGO  | 8547840           |
| DEPLOYMENT_ODO          | 9112320           |

Preparing a commit now.

As always, good took time to validate them.

**Comment by SmartArray** [comment]
I pushed several commits this morning to fix the wrong Difficulty that was printed out when calling `getblockchaininfo()`.

Also I fixed several other things such as incorrect computed block versions.

Unfortunately, there is still one warning left (versionbit 12 is active and unknown).

**Review by JaredTate — DISMISSED** [review]
ACK. This is by far the largest single PR we have ever done & the most comprehensive testing & upgrade we have ever done. I think this PR is now ready to be merged into development for further work. Yes, there are some tests to sort, and a few other improvements to make but that would be much more easily done in the develop branch while working on specific features.

I am of the opinion we should never be doing collaborative work out of personal accounts, which is what we are doing now and it's taking longer to test and improve. Anything unfinished should be broken down into easier to tackle features in its own feature branch where numerous people can work on it. 

It would be great to migrate the tasks on this list to an 8.22 beta release attack list, with the addition of more planned fixes/ improvements as well. A very clearly defined feature list for an 8.22 MVP (minimum viable product) would really help the community and devs get this over the finish line. Thank you to everyone who has helped with this!

**Comment by JaredTate** [comment]
Just opened a new DigiByte v8.22.0 Beta MVP To Do Task List: https://github.com/DigiByte-Core/digibyte/issues/87

**Review by JaredTate — DISMISSED** [review]
ACK

**Review by JaredTate — APPROVED** [review]
tACK. Now that we have the tests finished let's get this merged into develop. Continuing to create a PR into PR's is getting complicated.

**Review by SmartArray — APPROVED** [review]
tACK

**Review by BouwmanR — APPROVED** [review]
cACK

**Review by BouwmanR — APPROVED** [review]
cACK

**Review by BouwmanR — APPROVED** [review]
cACK

**Review by BouwmanR — APPROVED** [review]
cACK

**Review by BouwmanR — APPROVED** [review]
cACK

**Review by BouwmanR — APPROVED** [review]
cACK

**Pull request merged**
