### PR TITLE
Refactor DandelionShuffleThread to run in connection scheduler

### PR DESCRIPTION
**Pull request by barrystyle**
This PR refactors the dandelionshuffle thread, to run as a scheduler function which gets called once a second.

### CODE REVIEW

**Comment by SmartArray** [comment]
### Issue validated using Instruments.

@barrystyle is 100% right about the blocking loop that causes the CPU time of that thread to spin intensely, which is definitely far too inefficient.

Bildschirmfoto 2021-08-14 um 07 09 49


The current implementation only enters `DandelionShuffle()` (line 1798) every once in a while. I believe that the interval of 1 second - as suggested by @barrystyle - is fairly sufficient. We may also bump that number higher.

https://github.com/DigiByte-Core/digibyte/blob/3e6a19a16303bbe861d8de9e662013660aadc5ba/src/net.cpp#L1791-L1798

Also big thumbs up to use the node's scheduler instead of a thread, which, from the looks, should be fine as `DandelionShuffle()` has a low complexity. This is the only thing we will need to validate once more before ACKing this PR.

**Comment by barrystyle** [comment]
just removed the actual thread definition and 'on shutdown' thread cleanup

**Comment by JohnnyLawDGB** [comment]
So basically inserting breaks between CPU requests? Genius.

**Comment by SmartArray** [comment]
I just validated that the complexity of `DandelionShuffle()` is low enough to run in a scheduler. It took about 0-1ms per execution, which is insignificant.

**Furthermore I pushed two more commits.**
https://github.com/DigiByte-Core/digibyte/pull/65/commits/3a7b9fd0b5a64fbae72334ae1bc9711d8be35e1e renamed the function as it isn't a thread anymore.
https://github.com/DigiByte-Core/digibyte/pull/65/commits/48227d4a07d149117e5c97785972b2aa953064c4 exported the scheduler interval to an external constant.

**Review by SmartArray — APPROVED** [review]
ACK

**Review by gto90 — APPROVED** [review]
ACK

Great work on this performance improvement @barrystyle .  One thing I would love to start working towards is some unit test coverage around the Dandelion code, but this is great for now.

**Review by JaredTate — APPROVED** [review]
ACK. Looks good. Tested & working. Thanks for doing this Barry!

**Pull request merged**
