### PR TITLE
Disable RBF transaction signalling

### PR DESCRIPTION
**Pull request by barrystyle**
To complement the Dandelion implementation; prevent signalling RBF on transactions generated from the UI. Other functions will remove unaffected (a soft-disable).

### CODE REVIEW

**Comment by SmartArray** [comment]
utACK.

This corresponds to `TODO-002` from the list that I composed here: https://github.com/DigiByte-Core/digibyte/pull/63#issue-706477793

**Review by SmartArray — APPROVED** [review]
utACK.

This corresponds to `TODO-002` from the list that I composed here: https://github.com/DigiByte-Core/digibyte/pull/63#issue-706477793

**Review by fgabelmannjr — APPROVED** [review]
utACK

**Review by fgabelmannjr — APPROVED** [review]

**Review by gto90 — APPROVED** [review]
utACK

**Review by JaredTate — APPROVED** [review]
ACK. Compiles, runs, sends, GUI shows it removed.  

However during the process I noticed we have some theming issues. The icons in boxes to the right of Pay To box are not showing on send page like they should, but this issue was already there.

Before PR:

Screen Shot 2022-01-28 at 8 05 14 AM

After PR:

Screen Shot 2022-01-28 at 7 55 43 AM

**Pull request merged**
