### PR TITLE
Add-Seed-Node

### PR DESCRIPTION
**Pull request by Quakeitup**
Add dedicated seed node.

### CODE REVIEW

**Review by SmartArray — APPROVED** [review]
ACK

**Comment by saltedlolly** [comment]
Tested: https://www.whatsmydns.net/#A/seed.quakeguy.com

**Review by saltedlolly — APPROVED** [review]
tACK

**Review by j50ng — APPROVED** [review]
tACK- good work Paul!

**Review by ycagel — APPROVED** [review]
aCK - Great work!

**Pull request merged**
