### PR TITLE
Show progress percentage

### PR DESCRIPTION
**Pull request by cdonnachie**
Show process percentage on startup for loading and indexing blocks

image

image

### CODE REVIEW

**Comment by saltedlolly** [comment]
@cdonnachie Another small change I noticed between 7.17.3 and 8.22.0-rc2 is that the startup messages appended three periods "..." in v7 and a single elipsis character "…" in v8. I actually had to set up the rule below to fix this so the messaging displays correctly otherwise the right hand border appears of the Status Monitor appears a few characters askew for some reason.

```
    if [ "$DGB_ERROR_MSG" = " Rewinding blocks…" ]; then
        DGB_ERROR_MSG=" Rewinding blocks..."
    elif [ "$DGB_ERROR_MSG" = " Loading block index…" ]; then
        DGB_ERROR_MSG=" Loading block index..."
    fi
```

It looks like you actually fixed this when you added the percentage. :)

**Review by digicontributer — APPROVED** [review]
ack

**Review by gto90 — APPROVED** [review]
cACK

**Review by j50ng — APPROVED** [review]
cACK- looking forward to see this on the next release candidate along with the other fixes that speed up the synching.  Great to see your contributions @cdonnachie!

**Pull request merged**
