### PR TITLE
Max / Rpc tx fee.

### PR DESCRIPTION
**Pull request by ghost**
**Max tx fee**

src/node/transaction.h
 **COIN / 10**  >>  **COIN * 100**

https://github.com/DigiByte-Core/digibyte/blob/9eb291ed432abe4af6e32cc1ed1f138cb8876524/src/wallet/wallet.h#L100

### CODE REVIEW

**Review by gto90 — DISMISSED** [review]
cACK

Thank you for the contribution!

**Comment by ghost** [comment]
> cACK
> 
> Thank you for the contribution!

I change one value. Hope you can review again.
4294967295 > 4000000000

**Review by gto90 — DISMISSED** [review]
cACK

**Review by ycagel — DISMISSED** [review]
cACK

**Comment by ghost** [comment]
Sorry i remove some code from the pr. Now the pr is 100% working! Next time i will do more tests before making a PR. i think i use yesterday the wrong binary. The old RPC value's are working correctly. 0.1dgb / 100dgb.

**Review by JaredTate — APPROVED** [review]
ACK. Compiles & runs. Looks good. Thank you for the work on this!

**Review by ycagel — APPROVED** [review]
cACK. Thanks @Jongjan88!

**Review by gto90 — APPROVED** [review]
cACK

**Pull request merged**
