### PR TITLE
Fix: Functional Tests

### PR DESCRIPTION
**Pull request by SmartArray**
## Fix: Functional Tests

160 commits later, this PR finally fixes all 158 failing functional test by adapting them to the DigiByte network and chainparams.

Before this PR can be tested and merged, https://github.com/DigiByte-Core/digibyte/pull/89 needs to be accepted and merged because the functional tests will only run through if the core-related issues are fixed.

In order to fix the tests, it was required to
- generate new test vectors
- respect lower `COIN_MATURITY` parameter
- add `scrypt` as a python library that will be called during the tests
- add `-easypow` that turns off MultiAlgo during tests that are executed in regtest environment
- add a testnet checkpoint
- adapt higher absolute fees
- fix several mempool bugs
- and more

### CODE REVIEW

**Review by JaredTate — APPROVED** [review]
ACK. Once again amazing work @SmartArray. Having these tests working is a fundamental step towards a very stable 8.22. The client compiles, runs, and works great.

**Review by gto90 — APPROVED** [review]
ACK

**Comment by ghost** [comment]
❤️

**Review by ycagel — APPROVED** [review]
cACK

**Pull request merged**
