### PR TITLE
Fix 10 Functional Tests

### PR DESCRIPTION
**Pull request by JaredTate**
This PR fixes 10 functional tests.

To test this:

Compile:

```
  ./autogen.sh
  ./configure
  make -j 8
```
Run Specific Functional Tests
```
test/functional/test_runner.py rpc_packages.py p2p_addr_relay.py feature_coinstatsindex.py wallet_abandonconflict.py wallet_avoidreuse.py wallet_txn_clone.py --jobs=2
```
Screenshot 2024-03-10 at 9 20 34 AM

### CODE REVIEW

**Review by gto90 — APPROVED** [review]
utACK

**Comment by ghost** [comment]
10 test are passing.
Screenshot from 2024-03-10 16-48-52

**Review by ghost — APPROVED** [review]
utACK

**Review by ycagel — APPROVED** [review]
cACK. Great work @JaredTate!

**Pull request merged**
