### PR TITLE
Bump RC 3, Year & Standardize Release Version Format

### PR DESCRIPTION
**Pull request by JaredTate**
This PR bumps the release candidate version to 3 and year to 2024. @saltedlolly brought up great points about standardizing release version formats here https://github.com/DigiByte-Core/digibyte/issues/138. I think the prefix such as "digibyte-8.22.0-rc3" and stick to all lower case makes sense for a filename for binary releases.

The release version is set here in code:
https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/configure.ac#L2-L7

Since 8.22 is now compiled using the new guix process and not the old gitian building process the prefix "digibyte-8.22.0-rc3" was actually manually added to previous rc1& 2 releases. 

In the past the os file for each gitian build handled it, like here: 
https://github.com/DigiByte-Core/digibyte/blob/b75fea614b5e86f89a4759cdcfdc8d38635b50cf/contrib/gitian-descriptors/gitian-linux.yml#L2

### CODE REVIEW

**Review by ycagel — APPROVED** [review]
cACK. Thanks for all your efforts @JaredTate!

**Review by gto90 — APPROVED** [review]
ACK

**Comment by saltedlolly** [comment]
Thanks @JaredTate. Does this also ensure that the extracted folder from the binary download will be formatted 'digibyte-8.22.0-rc3' or does that need to be set somewhere else? That was the other thing that had changed between RC1 and RC2. (In RC2 the extracted folder was called 'digibyte-af42429717ac' as I mentioned in #138.)

Should we document this somewhere so it is clear for the future?

Thank you for doing this. Standardizing this means future DigiByte releases will be handled by DigiNode Tools out the box.

**Review by j50ng — APPROVED** [review]
ACK

**Pull request merged**
