### PR TITLE
Fix 10 Functional Tests

### PR DESCRIPTION
**Pull request by ghost**
**Compile:**

```
./autogen.sh
./configure
make -j 8
```

test/functional/test_runner.py --jobs=8

**OR**

python rpc_net.py
python wallet_fallbackfee.py --descriptors
python wallet_fallbackfee.py --descriptors
python wallet_labels.py --descriptors
python wallet_labels.py --legacy-wallet
python wallet_listsinceblock.py --descriptors
python wallet_listsinceblock.py --legacy-wallet
python wallet_watchonly.py --legacy-wallet
python wallet_watchonly.py --usecli --legacy-wallet
python wallet_descriptor.py --descriptors

### CODE REVIEW

**Review by gto90 — DISMISSED** [review]
utACK

Thank you @Jongjan88

**Comment by JaredTate** [comment]
So looks like `test/functional/test_runner.py rpc_net.py` still fails for me:
Screenshot 2024-03-06 at 10 39 12 AM

**Comment by ghost** [comment]
Screenshot from 2024-03-06 18-45-23

fixed

**Review by JaredTate — APPROVED** [review]
ACK. Sweet, they all pass for me now, looks good, the wallet compiles and runs. Great work!

**Review by ycagel — APPROVED** [review]
cACK. Thanks @Jongjan88!

**Review by gto90 — APPROVED** [review]
utACK

**Pull request merged**
