### PR TITLE
Added icons for RC3 and RC4

### PR DESCRIPTION
**Pull request by saltedlolly**
Quickly did these by editing the existing logo file. We could replace rc3 logo and replace the release. At least then people know what version they are running.

### CODE REVIEW

**Comment by ghost** [comment]
Good work @saltedlolly !
Screenshot from 2024-02-04 19-43-04

**Review by ycagel — APPROVED** [review]
ACK.

**Review by ghost — APPROVED** [review]
ACK.

**Review by JaredTate — APPROVED** [review]
ACK. Compiles, runs & looks great! Thanks for doing this and thinking ahead with RC4. I canceled my Adobe membership last fall to save some $$, so I don't have an easy way to edit these.

Screenshot 2024-02-05 at 3 09 30 PM

**Comment by JaredTate** [comment]
> ACK.

Looks like you need to hit the "review changes" in the upper right-hand corner to "approve" so it provides a 3rd check mark approval. Thanks for helping with reviews & all your work!

**Comment by ghost** [comment]
Screenshot from 2024-02-05 23-13-50

i did but my check is not the same color ^^

Screenshot from 2024-02-05 23-16-28


Update: now its blue! ty

**Comment by JaredTate** [comment]
> Screenshot from 2024-02-05 23-13-50
> 
> i did but my check is not the same color ^^
> 
> Screenshot from 2024-02-05 23-16-28
> 
> Update: now its blue! ty

It should work now, there was a permissions issue in the organization. Cheers

**Comment by saltedlolly** [comment]
@Jongjan88 and myself are only reviewers so our approvals never count towards one of the three required approvals. I am okay with that as I am not a C++ dev (though I would not approve anything I don't understand). On the other hand Jan is a C++ dev so he IS qualified to review changes, if and when the core devs want to allow him that responsibility.

**Comment by JaredTate** [comment]
> @Jongjan88 and myself are only reviewers so our approvals never count towards one of the three required approvals. I am okay with that as I am not a C++ dev (though I would not approve anything I don't understand). On the other hand Jan is a C++ dev so he IS qualified to review changes, if and when the core devs want to allow him that responsibility.

He should be good to go now, and I have no problem adding you as a full reviewer either. You have contributed a ton and are very active. I will ask the other guys what they think. It would be great to have more reviewers for continuous development.

**Comment by saltedlolly** [comment]
@JaredTate I was trying to figure out how to help fix the build process to ensure the filenames and folder names are correct, as previously discussed. Is it in this repo, or somewhere else? https://github.com/DigiByte-Core/DigiByte-GUIX-Docker

**Comment by JaredTate** [comment]
That is for the docker container, not the actual GUIX build process. I think the code for filenames is here, but not 100% sure where the folder names are drawn from in GUIX code. The file names change again after the complete formal signing process. Part of the signing process for a formal release includes the commit hash in the filename/folder to verify the commit the binaries are compiled from. 

https://github.com/DigiByte-Core/digibyte/blob/3c77decac7242a97d255b5273f8207836b67ce9a/contrib/guix/guix-build#L315-L329

**Pull request merged**
