### PR TITLE
Fix 4 Functional Tests

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes 4 functional tests.

To test this:

Compile:

  ./autogen.sh
  ./configure
  make -j 8

Run Specific Functional Tests
```
python rpc_createmultisig.py --descriptors 
python rpc_createmultisig.py --legacy-wallet
```
Update
```
wallet_coinbase_category.py --descriptors
wallet_coinbase_category.py --legacy-wallet
```

### CODE REVIEW

**Review by JaredTate — DISMISSED** [review]
ACK. Compiles & runs good. 
Screenshot 2024-03-11 at 10 02 40 AM

**Review by ycagel — DISMISSED** [review]
cACK. Thanks @Jongjan88!

**Review by gto90 — APPROVED** [review]
utACK

**Review by JaredTate — APPROVED** [review]
ACK. Compiles and runs good! 
Screenshot 2024-03-11 at 5 42 08 PM

**Review by ycagel — APPROVED** [review]
cACK. Thanks @Jongjan88!

**Pull request merged**
