### PR TITLE
Revert "Stop creating bdb ( QT ) && Warn if the loaded wallet is legacy"

### PR DESCRIPTION
**Pull request by ghost**
Reverts DigiByte-Core/digibyte#227

https://github.com/DigiByte-Core/digibyte/issues/239#issuecomment-2120851953

--------------------
After this we can also revert: https://github.com/DigiByte-Core/digibyte/pull/213 ( Make descriptor wallets by default  )

### CODE REVIEW

**Comment by JaredTate** [comment]
Hey @Jongjan88 I was just in the process of responding to this. I think its a good idea to have new wallets default to descriptor as we do want to push people that way. I just think we should be able to still allow users to create legacy wallets/ addresses from within the GUI if needed. 

For example, to get DigiHash pool working without a significant re-write of the pool I had to use the console to get legacy addresses from inside the GUI client. A process that's possible, but not easy for normal users. I think there are several instances where a user should be able to create a legacy wallet easily from inside the client.

But we really should try and push people to descriptor wallets, but I think that change will take time.

**Comment by ghost** [comment]
**This is still possible in the gui!!** Go to console then use this.
createwallet "wallet_name" ( false true false false false true false )

"If you enter **help** in the console you will get all these commands"

Screenshot from 2024-05-21 18-32-52

**Comment by JaredTate** [comment]
> **This is still possible in the gui!!** Go to console then use this. createwallet "wallet_name" ( false true false false false true false )
> 
> "If you enter **help** in the console you will get all these commands"
> 
> Screenshot from 2024-05-21 18-32-52

Yes, I mentioned that above:

>  "I had to use the console to get legacy addresses from inside the GUI client. A process that's possible, but not easy for normal users."

The console is not beginner-friendly. I think we should make things as easy as we can for users, it's already hard enough.

**Comment by ghost** [comment]
The only people who will ever need to create a legacy wallet are developers with some legacy code and they can do it easily via the console. Normal users should have no need to use a legacy wallet.

**Comment by JaredTate** [comment]
> The only people who will ever need to create a legacy wallet are developers with some legacy code and they can do it easily via the console. Normal users should have no need to use a legacy wallet.

If a normal user tries to mine on an existing pool or use a wallet on older exchanges they might need to generate legacy use cases. I can think of other instances.

**Comment by ghost** [comment]
> > The only people who will ever need to create a legacy wallet are developers with some legacy code and they can do it easily via the console. Normal users should have no need to use a legacy wallet.
> 
> If a normal user tries to mine on an existing pool or use a wallet on older exchanges they might need to generate legacy use cases. I can think of other instances.

I think you are confusing legacy wallets with base58 addresses. You can still make base58 addresses with the descriptor wallet

**Comment by ghost** [comment]
This PR is open. So you can approve.

**Pull request closed without merging**
