### PR TITLE
test: correct blockchain_tests

### PR DESCRIPTION
**Pull request by barrystyle**
This PR corrects the unit tests for blockchain_tests.cpp

### CODE REVIEW

**Comment by gto90** [comment]
@barrystyle , thank you for your contribution.  This looks mostly good to go but I am wondering if you edit your PR with the following:

- Re-Target the PR to point to `develop`.  We are following the GitFlow model and will not be accepting PRs directly into `master`.
- Could you provide a more detailed description regarding where you derived the parameter change to the `RejectDifficultyMismatch()` method?
- Could you add some information on how reviewers should review and test your change?  It does not need to be particularly verbose.

Many thanks for your kind contribution!

**Comment by barrystyle** [comment]
Bitcoin's genesis block has nbits set to 0x1d00ffff (sha256d diff1), which is target 00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff (equivalent to difficulty 1.0). Digibyte's genesis block is scrypt (which in itself has a different work factor to sha256d), nbits is set to 0x1e0ffff0 (scrypt diff1), which is target 00000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff (equivalent to difficulty 0.00024414).

**Comment by barrystyle** [comment]
This test is one of the first executed in the Bitcoin test suite (available under src/test), launched by running `./test_digibyte`.

**Review by gto90 — COMMENTED** [review]
ACK

**Review by gto90 — APPROVED** [review]

**Review by digicontributer — APPROVED** [review]
ACK

**Review by SmartArray — APPROVED** [review]
ACK

**Pull request merged**
