### PR TITLE
WIP: Implement RandomX algorithm

### PR DESCRIPTION
**Pull request by barrystyle**
PR implements the RandomX hashing algorithm, which is internally setup to suit any Monero style RandomX miner (such as xmrig).

### CODE REVIEW

**Comment by SmartArray** [comment]
I love what I see here. Thanks Barrystyle. People appreciate your hard work

**Comment by JohnnyLawDGB** [comment]
Nicely done Barry!

**Comment by oliverw** [comment]
@barrystyle Any hints on how a Mining Pool would handle this? Does a `getblocktemplate` RPC return a Monero/Cryptonote Style response containing `blocktemplate_blob`, `prev_hash`, `seed_hash`?

**Comment by barrystyle** [comment]
> @barrystyle Any hints on how a Mining Pool would handle this? Does a `getblocktemplate` RPC return a Monero/Cryptonote Style response containing `blocktemplate_blob`, `prev_hash`, `seed_hash`?

Effectively, getblocktemplate still works as standard on the digibyte end, the hard work is done by the pool (stratum reference: https://github.com/digibyte-project/yiimp). The pool presents an xmrig-compatible stratum interface that can be used directly with xmrig.

**Comment by oliverw** [comment]
> > @barrystyle Any hints on how a Mining Pool would handle this? Does a `getblocktemplate` RPC return a Monero/Cryptonote Style response containing `blocktemplate_blob`, `prev_hash`, `seed_hash`?
> 
> Effectively, getblocktemplate still works as standard on the digibyte end, the hard work is done by the pool (stratum reference: https://github.com/digibyte-project/yiimp). The pool presents an xmrig-compatible stratum interface that can be used directly with xmrig.

Interesting. Thank you.

**Comment by barrystyle** [comment]
> > > @barrystyle Any hints on how a Mining Pool would handle this? Does a `getblocktemplate` RPC return a Monero/Cryptonote Style response containing `blocktemplate_blob`, `prev_hash`, `seed_hash`?
> > 
> > 
> > Effectively, getblocktemplate still works as standard on the digibyte end, the hard work is done by the pool (stratum reference: https://github.com/digibyte-project/yiimp). The pool presents an xmrig-compatible stratum interface that can be used directly with xmrig.
> 
> Interesting. Thank you.

From memory the current algorithm implementation in the coin differs now from the one in the stratum, but they are very close. I will get the two synchronized in the near future.

**Comment by ycagel** [comment]
@barrystyle Do you want to pick this back up once we finish 8.22 development?

**Pull request closed without merging**
