### PR TITLE
Update SQLite 3.32.1(2020) to 3.45.2(2024)

### PR DESCRIPTION
**Pull request by ghost**
Depends update SQLite 3.32.1(2020) to 3.45.2(2024)

Fix lot off bugs and memory leak in SQLite.
Tested on Windows, Linux, Arm.

https://www.sqlite.org/changes.html

### CODE REVIEW

**Comment by saltedlolly** [comment]
Builds and runs on mac silicon
Screenshot 2024-03-17 at 11 36 35 am

**Review by ycagel — APPROVED** [review]
cACK. Appreciate the work @Jongjan88!

**Review by JaredTate — APPROVED** [review]
ACK. Great work! Compiles, runs good, gui works. `'make check' passes, doesn't seem to break any function tests we fixed.

Screenshot 2024-03-17 at 8 36 01 AM

**Comment by JaredTate** [comment]
Also looks like the same functional test failures we are still working though. So good to go.

Screenshot 2024-03-17 at 10 17 45 AM

**Review by gto90 — APPROVED** [review]
ACK

Thank you!

**Pull request merged**
