### PR TITLE
Fix libpng warning: iCCP: known incorrect sRGB profile

### PR DESCRIPTION
**Pull request by ghost**
**debug.log:** GUI: libpng warning: iCCP: known incorrect sRGB profile
1prob

Update sRGB profile of 49 images in src/qt/res/icons/

After PR:
fix

### CODE REVIEW

**Comment by ghost** [comment]
Maybe it also fix this on Windows QT. Not tested yet:

Screenshot from 2024-02-02 00-14-12

https://github.com/DigiByte-Core/digibyte/issues/164#issue-2106570920

**Comment by beggsdl** [comment]
I will test this to see if it helps with #164

**Comment by ghost** [comment]
> I will test this to see if it helps with #164

Ty! I don't think it will fix PR164. But maybe it helps with some errors in your log.

**Comment by JaredTate** [comment]
Thanks for looking into this. So this compiles and runs, but from what I can see the only thing actually changing is the addition of an empty digibyte.ico file. The ICO file format is an image file format for computer icons in Microsoft Windows. So until we add the complete digibyte.ico file back this won't change anything on windows and does nothing for other distros.

**Comment by saltedlolly** [comment]
It would be nice to give the icons and QT UI a little polish for v8. Nothing drastic, just something to give it that new car smell. No need to change the logo, just swap it for a polished version. I like those 3D effect DigiByte logos Shane did.

**Comment by saltedlolly** [comment]
https://t.me/Shane_DGB_Media/354

IMG_20220801_225032_597

**Comment by saltedlolly** [comment]
MAybe it would be nice to change up the color scheme as well. DigiByte blue is great, but one of the nice things about the Bitcoin logo (and the DigiByte logo) is that they work in any color. I'm not a designer but I'm sure we could find someone to help.

**Comment by ghost** [comment]
> Thanks for looking into this. So this compiles and runs, but from what I can see the only thing actually changing is the addition of an empty digibyte.ico file. The ICO file format is an image file format for computer icons in Microsoft Windows. So until we add the complete digibyte.ico file back this won't change anything on windows and does nothing for other distros.

Look in your debug.log the warning/error is gonne.( libpng warning: iCCP: known incorrect sRGB profile) 
From every image i remove the incorrect sRGB profile.

This are the old and new images files. Look at the size of each image.
Screenshot from 2024-02-02 18-58-23

Screenshot from 2024-02-02 19-04-18

**Comment by JaredTate** [comment]
> MAybe it would be nice to change up the color scheme as well. DigiByte blue is great, but one of the nice things about the Bitcoin logo (and the DigiByte logo) is that they work in any color. I'm not a designer but I'm sure we could find someone to help.

If someone has the time to upgrade the icons by all means we can do it. I am not a designer either. I will say on macOS it uses your operating system theme colors, so you could get some wonky looks. For example this is how my client looks on my mac:

Screenshot 2024-02-02 at 11 06 18 AM

**Comment by JaredTate** [comment]
> > Thanks for looking into this. So this compiles and runs, but from what I can see the only thing actually changing is the addition of an empty digibyte.ico file. The ICO file format is an image file format for computer icons in Microsoft Windows. So until we add the complete digibyte.ico file back this won't change anything on windows and does nothing for other distros.
> 
> Look in your debug.log the warning/error is gonne.( libpng warning: iCCP: known incorrect sRGB profile) From every image i remove the incorrect sRGB profile.
> 
> This are the old and new images files. Look at the size of each image. Screenshot from 2024-02-02 18-58-23
> 
> Screenshot from 2024-02-02 19-04-18

Ah ok, I now see what you are talking about with sRGB. Github still shows the digibyte.ico being blank though. I see the deletions and additions with different sRGB profile.

**Comment by Jongjan88** [comment]
> Ah ok, I now see what you are talking about with sRGB. Github still shows the digibyte.ico being blank though. I see the deletions and additions with different sRGB profile.

Yes i see but in my pr it is correct. I will try to fix it. one moment

**Comment by ghost** [comment]
Screenshot from 2024-02-02 19-22-25

It is a GitHub problem! This fix was not intended for Windows. Global fix. But I'm now testing it in Windows and it seems to fix that to. This https://github.com/DigiByte-Core/digibyte/issues/164#issue-2106570920 issue. You see lot of errors in debug.log. On my windows install i don't see them. With this PR. Not yet tested without this PR.

**Comment by beggsdl** [comment]
> It would be nice to give the icons and QT UI a little polish for v8. Nothing drastic, just something to give it that new car smell. No need to change the logo, just swap it for a polished version. I like those 3D effect DigiByte logos Shane did.

The icons are already updated from v7 (Windows OS, v7 on top, v8 on bottom).
image

I do like that logo you posted.  The logo is currently the same between v7 and v8, so I think a refresh of that would look good.

**Comment by beggsdl** [comment]
> It is a GitHub problem! This fix was not intended for Windows. Global fix. But I'm now testing it in Windows and it seems to fix that to. This [#164 (comment)](https://github.com/DigiByte-Core/digibyte/issues/164#issue-2106570920) issue. You see lot of errors in debug.log. On my windows install i don't see them. With this PR. Not yet tested without this PR.

Specifically which errors in the debug.log file on Windows are you referring to? I am curious, because all those errors in what I had posted would not show up for many hours of running. And then several hours after they appeared, it would crash.

**Comment by ghost** [comment]
> > It is a GitHub problem! This fix was not intended for Windows. Global fix. But I'm now testing it in Windows and it seems to fix that to. This [#164 (comment)](https://github.com/DigiByte-Core/digibyte/issues/164#issue-2106570920) issue. You see lot of errors in debug.log. On my windows install i don't see them. With this PR. Not yet tested without this PR.
> 
> Specifically which errors in the debug.log file on Windows are you referring to? I am curious, because all those errors in what I had posted would not show up for many hours of running. And then several hours after they appeared, it would crash.

Ok, I'm curious to see if your node still crashes. and if so, share the debug.log please. Is the node running with this pr?

**Review by JaredTate — APPROVED** [review]
ACK. I went ahead and GUIX built the windows.exe binary. Everything looks good, compiles and runs. Thanks for this update! 
dgbwallet-windows

**Comment by ghost** [comment]
> ACK. I went ahead and GUIX built the windows.exe binary. Everything looks good, compiles and runs. Thanks for this update! dgbwallet-windows

Thank you for all your time to review. I would try to provide more text and explanation in the next PR.

**Comment by saltedlolly** [comment]
> > MAybe it would be nice to change up the color scheme as well. DigiByte blue is great, but one of the nice things about the Bitcoin logo (and the DigiByte logo) is that they work in any color. I'm not a designer but I'm sure we could find someone to help.
> 
> If someone has the time to upgrade the icons by all means we can do it. I am not a designer either. I will say on macOS it uses your operating system theme colors, so you could get some wonky looks. For example this is how my client looks on my mac:
> 
> Screenshot 2024-02-02 at 11 06 18 AM

Does QT handle switching between dark and light mode? Can it support adding a difent logo for dark mode and light mode on Mac?

**Comment by ghost** [comment]
> > > MAybe it would be nice to change up the color scheme as well. DigiByte blue is great, but one of the nice things about the Bitcoin logo (and the DigiByte logo) is that they work in any color. I'm not a designer but I'm sure we could find someone to help.
> > 
> > 
> > If someone has the time to upgrade the icons by all means we can do it. I am not a designer either. I will say on macOS it uses your operating system theme colors, so you could get some wonky looks. For example this is how my client looks on my mac:
> > Screenshot 2024-02-02 at 11 06 18 AM
> 
> Does QT handle switching between dark and light mode? Can it support adding a difent logo for dark mode and light mode on Mac?

At the moment there is only one logo for dark and light mode.

**Review by ycagel — APPROVED** [review]
cACK. Thank you to everyone for their efforts in testing.

**Review by gto90 — APPROVED** [review]

**Comment by gto90** [comment]
cACK.

Thanks for the effort on cleaning up all these assets!

**Pull request merged**
