### PR TITLE
Return the fee in satoshis for a size of 1000 bytes

### PR DESCRIPTION
**Pull request by ghost**
Screenshot from 2024-03-06 23-14-21

test/functional/test_runner.py

**PR184**
66 Failed

**PR184 && PR185**
57 Failed

### CODE REVIEW

**Comment by JaredTate** [comment]
I am not 100% sure what exactly this should be. I need to break down the math & logic and write it down so it's clear to everyone. Once we do that, it should be smooth sailing for all the fee issues. We want the fee high enough to prevent cheap spam attacks, and low enough for room to grow & incentive for cheap TX's on DGB. Last thing we want is if DGB 10x in next year and transactions get spendy for everyone.

**Comment by ghost** [comment]
> I am not 100% sure what exactly this should be. I need to break down the math & logic and write it down so it's clear to everyone. Once we do that, it should be smooth sailing for all the fee issues. We want the fee high enough to prevent cheap spam attacks, and low enough for room to grow & incentive for cheap TX's on DGB. Last thing we want is if DGB 10x in next year and transactions get spendy for everyone.

getfee

It is calculate the fee over 1000 bytes. I think we should change fees in other places like mintxfee and default_min_relay_tx_fee.

**Update**
tested

i did couple of test with core wallet. And this pr. No problems so far.

**Review by JaredTate — APPROVED** [review]
ACK. Compiles & runs. Ah yes, this function returns the fee in satoshis for a 1000-byte transaction. It indeed should call GetFee(1000) instead of GetFee(100000) to correctly represent a kilobyte (1000 bytes) of transaction data.

**Review by ycagel — APPROVED** [review]
cACK. Thanks @Jongjan88!

**Review by gto90 — APPROVED** [review]
utACK

Thank you @Jongjan88 and @JaredTate

**Comment by ghost** [comment]
Thanks! @JaredTate @ycagel @gto90 !! Lets go to 50..

**Pull request merged**
