### PR TITLE
Update keys.txt

### PR DESCRIPTION
**Pull request by j50ng**
Added GPG key

### CODE REVIEW

**Comment by mtaipe** [comment]
Are all those in that list Digibyte developers? What is the purpose of this file?

**Review by SmartArray — DISMISSED** [review]
ACK

**Comment by SmartArray** [comment]
> Are all those in that list Digibyte developers? What is the purpose of this file?

It specifies the developer's gpg public keys.

We are about to sign a release candidate for DigiByte Core 8.22.

The more developers help signing the release, the more trust it yields.

If you have an Ubuntu, basic knowledge about build environments and would like to help out, you can try this guide that I have just written:

https://github.com/DigiByte-Core/DigiByte-GUIX-Docker

**Review by JaredTate — DISMISSED** [review]
ACK

**Review by ycagel — DISMISSED** [review]
ACK

**Review by JaredTate — APPROVED** [review]

**Review by ycagel — APPROVED** [review]
cACK

**Review by gto90 — APPROVED** [review]
cACK

**Pull request merged**
