### PR TITLE
Bump DigiByte logo to 8.22.0-RC5

### PR DESCRIPTION
**Pull request by beggsdl**
Replaced the digibyte_wallet.png file with one for 8.22.0-RC5

### CODE REVIEW

**Comment by beggsdl** [comment]
I noticed changes had been made to bump version to RC5, so here is a logo to go along with that change.

**Comment by ycagel** [comment]
@JaredTate @gto90 Are we still going with another release candidate? Is it possible to ship out the final release?

**Comment by gto90** [comment]
> @JaredTate @gto90 Are we still going with another release candidate? Is it possible to ship out the final release?

Let's see what Jared thinks, but I am not opposed.  I know that we were pushing or a final release but it also wouldn't hurt to do a final release candidate.  No harm in that.

**Review by JaredTate — APPROVED** [review]
Awesome, thank you for doing this! I think an RC5 makes good sense. Especially if we can reset testnet, test taproot activation and get dandelion working. We could use help with dandelion testing.

**Review by ycagel — APPROVED** [review]
cACK. Thank you @beggsdl!

**Pull request merged**
