### PR TITLE
DGB Seed Nodes Update 

### PR DESCRIPTION
**Pull request by JaredTate**
Signed-off-by: Jared Tate <13957390+JaredTate@users.noreply.github.com>

After looking through the hardcoded seed nodes for DigiByte-Core as well as [digibytewallet-core](https://github.com/DigiByte-Core/digibytewallet-core/blob/master/BRChainParams.h#L48) for the mobile wallets both codebases need to be updated with more seeds to help fix connection issues now being experienced, especially the light wallets. 

Running a DGB core seed node is simple. You just need to have a URL (example: seed.digibyte.io) and a DigiByte Core full node of the latest version that's running 24/7 at that address. It's also helpful to add "maxconnections=800" or any higher number to allow more than 8 peers at a time in the digibyte.conf file.

If you are interested in running a full-time seed node for the next few years to help the network out please mention it in a comment below with the URL. Let me know if you see any issues with seeds listed below.

```    
        //DigiByte Community Seed Nodes
        vSeeds.emplace_back("seed.digibyte.org"); // Website collective
        vSeeds.emplace_back("seed.digibyte.io"); // Jared Tate
        vSeeds.emplace_back("seed.digihash.co"); // Jared Tate
        vSeeds.emplace_back("dnsseed.esotericizm.site"); // DigiContributor
        vSeeds.emplace_back("seed.digibytefoundation.org"); // DigiByte Foundation
        vSeeds.emplace_back("seed.digiexplorer.info"); // DigiByte Foundation
        vSeeds.emplace_back("seed.digiassets.net"); // DigiByte Foundation
        vSeeds.emplace_back("digibyteblockexplorer.com"); // DigiByte Block Explorer
        vSeeds.emplace_back("dgb1.trezor.io"); // Trezor
        vSeeds.emplace_back("seed2.digibyte.io"); // Jared Tate
        vSeeds.emplace_back("seed3.digibyte.io"); // Jared Tate
        vSeeds.emplace_back("seed.digibyteblockchain.com"); // JS555
        vSeeds.emplace_back("seed.digibyte.host"); // SashaD
        vSeeds.emplace_back("seed.digibyteservers.io"); // ChillingSilence

### CODE REVIEW

**Review by SmartArray — APPROVED** [review]
ACK

**Comment by Quakeitup** [comment]
dgb.quakeguy.com

**Comment by ycagel** [comment]
cACK

**Comment by wiria** [comment]
dgb.nul.io

**Comment by barrystyle** [comment]
Had issues resolving the following few entries;
```
dnsseed.esotericizm.site
seed.digibytefoundation.org
seed.digibyteblockchain.com
```

**Comment by ChillingSilence** [comment]
It's more than that. It's not just that some are failing to resolve at a DNS level, but in addition many in the list are not dnsseeds, and checks on UDP 53 need to be done. This should not have been merged.

ONLY:
```
seed.digibyte.org
seed.digibyte.io
seed.digibyteservers.io
```
are correctly responding when checked with nslookup for example.

To my knowledge this list has absolutely *nothing* whatsoever to do with maxconnections, nor the node itself running on TCP port 12024.

**Comment by saltedlolly** [comment]
@Quakeitup I see you are running a full node at dgb.quakeguy.com

Would you be willing to also run a DigiByte Seeder alongside your full node? 

We need a few more DigiByte Seeders: https://github.com/DigiByte-Core/digibyte-seeder

**Comment by Quakeitup** [comment]
Yes of course. I'll need to migrate to better "hardware" first. It's been a
plan to move the node to a faster system for a while but this gives me the
push I needed. I'll add seed node that to the plan. If I had to give an ETA
I'd say online by March 1st.

Thanks,
Quakeitup

**Comment by saltedlolly** [comment]
@Quakeitup That's great to hear. It's worth mentioning that the resources required to run a DiiByte Seeder are very low - it is simply a lightweight DNS server so if you are already running a full node, then running a Seeder as well should be easy. I have written up a full tutorial [here](https://www.evernote.com/shard/s20/client/snv?noteGuid=46de28c1-9066-4ca5-8048-6f29f9e3bf52&noteKey=66077e0b3f969350ebefe4228d731425&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs20%2Fsh%2F46de28c1-9066-4ca5-8048-6f29f9e3bf52%2F66077e0b3f969350ebefe4228d731425&title=Setting%2Bup%2Ba%2BDigiByte%2BSeeder). 

We are also encouraging people to provide their name and contact info if they are running a seeder, given what an important piece of infrastructure it is. This way it is easy to contact them in the event of a problem. Details are in the document I have linked to.

**Comment by saltedlolly** [comment]
Can anyone tell me who manages seed.digibyte.org? It just says "Website Collective". It would be good to have a contact person for this. Is it @makyurt?

**Comment by saltedlolly** [comment]
@wiria You previously ran a DigiByte Node, but I don't see it any more. It would be really beneficial to have a DigiByte Seeder in Asia. Is this something you could help with? As you can see with the new seeder list, we are well covered in the US, but it would be nice to have Seeders in Asia and Europe: https://1drv.ms/w/s!AsTGLNLt5YBypgadXSi16NEPaXes

**Comment by saltedlolly** [comment]
Does anyone know who owns digibytefoundation.org ? It is hardcoded into v7.17.3 and says "DigiByte Foundation". Rudy tells me they do not own that domain - they use digibytefoundation.io only. Rudy thinks it may be owned by @JaredTate  or possibly Josiah?

**Pull request merged**
