### PR TITLE
Reward to 0 Code

### PR DESCRIPTION
**Pull request by JaredTate**
This pull request updates RegTest network settings to the same settings I used in my recent video where I demonstrated a fix for the DGB mining reward decay to go to 0 instead of 1. Also in this pull request, I provide the 1-line fix to make sure the reward goes to 0 and does not stay at 1 infinitely. 

Here is a link to the video where I demo the test & prove this fix:  https://www.youtube.com/watch?v=BcOOxoHXJ0I

The main issue is caused by 1 line of code:
` if (nSubsidy < COIN) {
        nSubsidy = COIN;
    }`
    
  Simply needs to be changed to:
  
  ` if (nSubsidy < COIN) {
        nSubsidy = o;
    }`
    
In addition to the regest changes I also changed a few more variables locally to speed up the previous DGB hardfork points. These local changes if anyone wants to test themselves were below, bottom line of each was test change to make network simulate changes faster with regtest mining. Note the below changes are not in this PR, this is just for reference.

```
if  (nHeight < 1440)
if (nHeight < 3)

else if (nHeight < 5760)
else if (nHeight < 6)

int64_t months = blocks * BLOCK_TIME_SECONDS / SECONDS_PER_MONTH;
int64_t months = blocks * 1;```

### CODE REVIEW

**Review by gto90 — DISMISSED** [review]
ACK

**Review by BouwmanR — DISMISSED** [review]
cACK

**Review by j50ng — DISMISSED** [review]
Concept ACK

**Review by ycagel — DISMISSED** [review]
cACK

**Comment by SmartArray** [comment]
Just tested the changes. These new parameters cause a lot of failed tests when rebased against `develop`.
I suggest we should leave the regtest params unchanged because MultiAlgo is definitely not covered in most of the functional tests and it would be painful to do that now. It's not a requirement to change these parameters, is it?

I would also suggest a second PR in which we just change the default value for `easyPow` to true (this argument needs to be removed then in all functional tests)

The fix of setting the emission to `0` instead of `COIN` is good of course. Jared, can you amend your latest commit?

**Review by SmartArray — APPROVED** [review]
ACK

**Review by ycagel — APPROVED** [review]
cACK

**Review by j50ng — APPROVED** [review]
cACK

**Pull request merged**
