### PR TITLE
Update Wallet Image to RC2

### PR DESCRIPTION
**Pull request by JaredTate**
Upddate wallet image to RC2. Soon as we do that we can create a new rc2 branch, tag it, build guix, and finally have a public test release for 8.22.

### CODE REVIEW

**Review by SmartArray — APPROVED** [review]
ACK

**Review by j50ng — APPROVED** [review]
ACK

**Review by gto90 — APPROVED** [review]
cACK

**Comment by ycagel** [comment]
ACK

**Pull request merged**
