### PR TITLE
Clean up seed servers (removed seed.digibyte.org)

### PR DESCRIPTION
**Pull request by saltedlolly**
Removed seed.digibyte.org - it has not worked in months

Also removed the old full nodes which were listed as seed servers. Neither seem to have a full node there any way.

### CODE REVIEW

**Comment by JaredTate** [comment]
Who was running seed.digibyte.org ? Also these changes to the progress bar, do you have a screenshot of what's being changed there? Cheers

**Comment by saltedlolly** [comment]
Sorry the progress bar got added by mistake. I pushed it to my repo and it got added to that PR. I'm trying to compile and test. I will remove it in a bit.

seed.digibyte.org is one of the great mysteries. I have been trying to find out for a year who ran it. Nobody seems to know. It definitely was a working seed server at one point but it has not worked since May ish. @Sbosvk tried to set up a new seeder to point the domain at but couldn't make it work. At this point I felt it best to remove it. We can maybe find a replacement.

**Comment by Sbosvk** [comment]
If anyone is able to set a new seeder up I am more than willing to point the DigiByte.org DNS to it.

**Review by gto90 — APPROVED** [review]
ACK

**Review by ycagel — APPROVED** [review]
ACK

**Review by j50ng — APPROVED** [review]
ACK

**Comment by saltedlolly** [comment]
A small thing, but I also thought it was better to start calling these "Seed Servers" or "DNS Seed Servers". Calling them Seeders can be a bit confusing because it could be you are referring to the list full nodes that also get hardcoded into DigiByte Core. Calling them servers (which they are) makes the distinction clearer.

**Comment by JohnnyLawDGB** [comment]
@renzoDD

**Pull request merged**
