### PR TITLE
Replace mentions of satoshi to digibit in QT (sat to dbit)

### PR DESCRIPTION
**Pull request by saltedlolly**
This is the first PR of fixes replacing mentions of satoshi with digibit. I have broken this into several PRs to make them easier to review. The two additional PRs will cover the QT locale and the tests. 

I have tested this on Apple Silicon.

Screenshot 2024-03-26 at 4 09 41 pm

Please review carefully to make sure I have not made any mistakes.

### CODE REVIEW

**Comment by JaredTate** [comment]
Looks good so far, thanks for taking time to do this @saltedlolly . This PR compiles for me, runs and changes appear to be correct in the GUI.

Screenshot 2024-03-26 at 11 01 57 AM

Also `make check` has no failures, so those 470 tests are not broken. 

Screenshot 2024-03-26 at 11 00 36 AM


I am currently running the python functional tests to see if anything is broken, but it takes about an hour to run 210 of them with:

`test/functional/test_runner.py --jobs=2`

**Comment by saltedlolly** [comment]
This PR, a long with the next two PRs, addresses #198

**Comment by JaredTate** [comment]
Looks like this PR is now breaking 8 functional tests: 

Screenshot 2024-03-26 at 12 21 09 PM

**Comment by saltedlolly** [comment]
I submitted updates to these functional tests in the other PR so that could be why. Let me run the tests at my end and see what happens.

**Comment by JaredTate** [comment]
> I submitted updates to these functional tests in the other PR so that could be why. Let me run the tests at my end and see what happens.

Ok cool, you can run just those tests with:

`test/functional/test_runner.py wallet_send.py wallet_basic.py rpc_psbt.py rpc_fundrawtransaction.py p2p_addr_relay.py`

If you have the fixes already it would be great to add to this PR so it can be tested. Impossible to test either PR if they are split up, and if we merge this PR as is we break the develop branch. Cheers

**Comment by ghost** [comment]
Nice work @saltedlolly but maybe only change the names in Digibyte-qt?

**Comment by mctrivia** [comment]
Please don't.  Satoshi is universally recognized now as 0.00000001  it may even become SI prefix some day if crypto really takes off.  Making up a new term when one is already exists is stupid.  It causes segregation when none is needed.

**Comment by saltedlolly** [comment]
@mctrivia The term "satoshi" is used for the smallest denomination of Bitcoin, but DigiByte is not Bitcoin. It only leads to confusion to have them the same - a DigiByte digibit/digisatoshi/dsat (whatever you want to call it) is also not equal to a Bitcoin Satoshi, as a percentage of the total supply. Furthermore,  the term Satoshi has never been used for DigiByte up till this point. I am of the opinion that it is sensible to standardize the term for DigiByte. This is why we have been having a discussion about it, and trying to do that.

**Comment by JaredTate** [comment]
Alight, that 2nd round of commits seems to get this working. Good work @saltedlolly This PR now compiles for me, runs, and has no test failures either with functional tests or unit tests: 

Screenshot 2024-03-26 at 2 17 38 PM

Screenshot 2024-03-26 at 2 19 58 PM

Screenshot 2024-03-26 at 2 17 44 PM


As for a debate on if this PR is needed or not, I am open too it, but I also think it would be a good idea to bring this up before the community and get more input. I am putting together a video for tomorrow and can propose it and see what people think. Maybe we could even organize a twitter poll, or other means to vote.

**Comment by mctrivia** [comment]
Satoshi is used by every utxo chain that uses 8 decimals to refer to the smallest unit.  It has very often been used by DigiByte and definetly does not cause confusion.   If we are talking about DigiByte and say it takes 600 sats to make an asset output everyone knows what that means.  It's even written as 600 sats everywhere it is written.

Any term but sats is just silly duplication of a term.

You wouldn't create a new prefix for 1/1000 of a Leter when you already have one for 1/1000 of a meter

**Comment by Sbosvk** [comment]
I find this more confusing and weird to be honest..if we are getting on the whole bit/byte train here, and 1 digibit is 0.00000001, then that would mean that 1 DigiByte is 0.00000008.

If anything, 1 DigiBit would be 0.125 DigiByte.

**Comment by mctrivia** [comment]
I agree if making up digibit it should be 1/8 of a DigiByte.  Though i don't think we should make that up

**Comment by JaredTate** [comment]
> I find this more confusing and weird to be honest..if we are getting on the whole bit/byte train here, and 1 digibit is 0.00000001, then that would mean that 1 DigiByte is 0.00000008.
> 
> If anything, 1 DigiBit would be 0.125 DigiByte.

This is a very fair argument indeed. A bit in its basic definition is very much defined and representative of 8 intuitively. Then again "bitcoin" has little to do with the # 8... so its open for debate for sure.

In the interest of time, and the fact we have people with old dgb wallets stuck due to the wallet import bug that's been fixed I propose we go ahead with an RC4 release before deciding on this issue fully. I will include this idea in a video update today for the community to discuss more. 

Given we have all tests passing again, and all the recent changes I think we are at a solid point for an RC4 to get out as a stable testing platform. We have a ton of changes already in RC4. 

Here are draft release notes: https://github.com/DigiByte-Core/digibyte/releases/tag/untagged-d52f12070983ee637d66

Tagged rc4 branch:  https://github.com/DigiByte-Core/digibyte/tree/release/v8.22.0-rc4

**Comment by saltedlolly** [comment]
At the end of the day it is just a word, and the impetus behind this is simply to create some standardisation in the naming. Based on the discussions in the issue thread for the last two weeks 'digibit' is what we had converged on. I was keen to get on with it, so yesterday went ahead with putting together a PR hoping to get it into RC4. It is obviously a bit frustrating for me having spent many hours working on it yesterday to only now have these concerns raised. It would have been helpful to have these opinions shared when it was being discussed in the Issues thread.

Having said that, I accept that there are diferent opinions on this so it might be wise to ask the community what their thoughts are. I personally believe that it is good to have a distinct name that is unique to DigiByte. The main reason I believe that several (but not all) UTXO chains still use the name Satoshi is that they have simply not yet come up with their own name. I do believe what it could cause confusion in a world where things are priced in Bitcoin sats. Maybe not for technical users but for everyone else. i also think it is good for DigiByte to stand apart from Bitcoin.

That is my opinion, but this is also not a hill I need to die on so if the community can settle on a name then let's pick something and stick with it. That was the main objective - to come up with a suitable term and stick with it. If everyone wants to stick with Satoshi then so be it.

Lastly, I personally am not that concerned about there being 8 bits in a byte but not 8 digibits in a DigiByte - we are not referring to data in this context anyway. It is simply a name for a unit of money and most users without a computer science background would not even notice. Though if others hate the name, perhaps we should continue this disussion in the issues thread to try and come up with something better.

**Comment by mctrivia** [comment]
@saltedlolly myself and others have talked about this alot before in telegram.  We didn't see this pull request until now or would have said something.  I am strongly in the camp of standardising prefix.

m=3 decimals
u=6 decimals
sat=8 decimal
n=9 decimals
p=12 decimals
f=15 decimals
a & gw=18 decimals(wish eth had just gone with the SI a instead of creating gw but it's here now)

across the board everyone agrees on these so why make up a new one?

**Comment by Sbosvk** [comment]
I understand your frustration, @saltedlolly, and had I known about this earlier I would've of course never waited so long to raise my opinion on the matter. This is just the way things go sometimes.

I get your point, but I also agree and disagree with Matthew. There is not much sense in creating a standardisation when they already exists, in fact it defeats the purpose of standardisation as a concept of everyone were to simply make up their own. Personally, I am neither fond of satoshis nor coming up with something new, I think it would be far more sensible and widely relatable to go with definitions that have already existed in math and economy for a long time.

As for ignoring the bit/byte I think this is not at all a good reasoning, as the entire idea behind the name of DigiByte is Digital Byte, so I think we would be ignorant to ignore this obvious relation between the two.

All this being said, I am not aware of any definition for an 8 decimal point number.

**Comment by Sbosvk** [comment]
Reading my own comment, I realised I don't really conclude anything.
- I think satoshi is the best available alternative, although I'm not a fan. If we really really have to, for what ever reason, not stick with that, I think we need to come up with something better than digibit because of the reason I have already mentioned in a previous comment.

**Comment by RenzoDD** [comment]
Unfortunately, thing in the industry are mostly based on patterns and @mctrivia is right, all UTXO chains have standardized the use of Satoshi as the minimun dividing unit. This change (altho it seems mostly visual on the wallet) might have significant impact for the future newcomers. DigiByte explorers use sats as the unit also. So in development terms this change is not necessarily positive.

**Comment by DGBNOOB** [comment]
I just read through the comments on the issue that lead up to the PR. In my opinion it seems hasty and cosmetic. The conversation on the issue began two weeks ago and at most the conversation was between four people. I’ll admit I don’t know the full benefits or ramifications of making this change but it seems the move is hasty. The other thought that came to mind was, shouldn’t this go through the DigiByte Improvement Proposals (DIP’s) process? I suggest going through the DIP’s process first since it touches Core and this isn’t a need, it’s more of a preference. Much respect for everyone here.

**Comment by saltedlolly** [comment]
I've just seen the twitter poll that was put up and looking at the comments it seems there are lots of opinions being shared. I agree that in hindsight it was probably a bit rushed, and @mctrivia and @Sbosvk do make some good points. It was not my intention to make a big issue over this. I agree we should go ahead with RC4 without it to allow time for further discussion. 

If we decide to stick with satoshi, it's worth noting that I did also fix several places in DigiByte Core where BTC is mentioned instead of DGB so it would still be good to get those fixes in.

**Comment by DGBarchie** [comment]
I think DigiBit is as good as it would get in terms of a satoshi/digisatoshi replacement.

I see some arguing here that a 'satoshi' is already standardized metric prefix of 10^-8. I don't necessarily see it that way - I think a satoshi is generally defined as "the smallest amount of BITCOIN possible" - which just happens to be 10^-8 BTC. 

This is why 'digisatoshi' exists, after all - the community naturally produced a DigiByte-specific alternative.

Zooming out, the name of the blockchain is DigiByte, using digibit is a fun play on words. If 1 Byte = 8 bits; why can't 1 DigiByte = 10^8 digibits — the ratio may not be "correct" but what exactly is a 'Digi-Byte' anyways!?

I think anyone who understands anything about crypto would understand what this means: 
Bitcoin:satoshi :: DigiByte:digibit

Just my thoughts!

I do think that this discussion is important & that this shouldn't be rushed

**Comment by saltedlolly** [comment]
> m=3 decimals
> 
> u=6 decimals
> 
> sat=8 decimal
> 
> n=9 decimals
> 
> p=12 decimals
> 
> f=15 decimals
> 
> a & gw=18 decimals(wish eth had just gone with the SI a instead of creating gw but it's here now)

Respectfully, I don't think deciding to call it a digibit/dbit instead of a satoshi/sat changes this in any way. Satoshi is a made up name that was chosen for the lowest denomination of Bitcoin. (8 decimals). Litecoin calls it a Litoshi. Zcash is a zatoshi. 

Furthermore, if and when 'satoshi' was ever to become a ISO standard name (which is unlikely in my view), this could always be revisited.

**Comment by saltedlolly** [comment]
A possible compromise which might be more universally accepted by the community could be to call it a **digisat (dsat)**. This would maintain a connection to the term Satoshi, while being distinct to DigiByte. It's also a lot less of a mouthful than DigiSatoshi.

**Comment by mctrivia** [comment]
Doing a Google search I can not find anyone using zsat or lsat.  Related to crypto

Also I should mention you can change on site and core wallet but all the 3rd party wallets will keep there fee indicator in sats/byte.  And many DigiByte related sites will stay sats because people not all will agree with the change.

**Pull request closed without merging**
