### PR TITLE
Fix for low fee 0.1DGB/KB

### PR DESCRIPTION
**Pull request by ghost**
**issue** [#169](https://github.com/DigiByte-Core/digibyte/issues/169) Minimum tx fee per kb and maxfee  

Screenshot from 2024-02-04 20-30-17

Screenshot from 2024-02-04 20-31-04

**https://github.com/DigiByte-Core/digibyte/releases/**
Screenshot from 2024-02-04 20-49-40

**After pr update:**
Minimal fee: 0.1DGB/KB
Total maximum custom fee: 100 DGB/transaction ($0,74) Before: 1 DGB/transaction ($0,0074) - 2024-02-06

### CODE REVIEW

**Comment by beggsdl** [comment]
Thanks @Jongjan88.  I will test this soon.

**Review by JaredTate — DISMISSED** [review]
ACK. Looks like [same issue](https://github.com/DigiByte-Core/digibyte/issues/169) I had run into, but I only tested up to 50 inputs. When I did 60 inputs I was able to recreate the problem so we didn't fully fix it with https://github.com/DigiByte-Core/digibyte/pull/159. Looks like this does fix this. I just tested it with 50+ inputs. Client compiles & runs.

**Review by ycagel — DISMISSED** [review]
cACK.

**Comment by ycagel** [comment]
@beggsdl Were you able to test this?

**Comment by beggsdl** [comment]
> @beggsdl Were you able to test this?

I think there is still an issue.  I will post some screenshots in a little bit.

**Comment by ghost** [comment]
> > @beggsdl Were you able to test this?
> 
> I think there is still an issue. I will post some screenshots in a little bit.

Screenshot from 2024-02-06 15-03-47


Windows and Linux bins with the update of this pr are online.

**Comment by beggsdl** [comment]
Here are testing results for the following:
- min fee/kB must be >= 0.1:  success
- max tx fee must be <= 100:  success

### Test proof

**Min fee/kB must be >= 0.1**
Typed 0.01
image

When moving out of the field, it reset to 0.1 (SUCCESS)
image


**Max TX fee must be <= 100**
Sent 1 000 000 DGB with default fee of 0.1 DGB/kB (SUCCESS)
image

Sent 1 000 000 DGB with fee of 1.0 DGB/kB (SUCCESS)
image

Attempted to send 1 000 000 DGB with fee of 2.0 DGB/kB, but failed due to TX fee being too large.  TX fee would have been 149.2 DGB. (SUCCESS)
image

**Comment by Jongjan88** [comment]
Attempted to send 1 000 000 DGB with fee of 2.0 DGB/kB, but failed due to TX fee being too large. TX fee would have been 149.2 DGB.

We cannot change the kB size. So if you have 75kb * 2dgb * 1.000.000 = 150dgb.
Then we need to change the 100 DGB/transaction limit. Don't think that is good.

You can easy send 75kb * 0.1dgb * 10.000.000 dgb =  75dgb

But i think with this kind of transactions use -maxtxfee ...

**Comment by ghost** [comment]
> Here are testing results for the following:
> 
>     * min fee/kB must be >= 0.1:  success
> 
>     * max tx fee must be <= 100:  success
> 
> 
> ### Test proof
> 
> **Min fee/kB must be >= 0.1** Typed 0.01 image
> 
> When moving out of the field, it reset to 0.1 image
> 
> **Max TX fee must be <= 100** Sent 1 000 000 DGB with default fee of 0.1 DGB/kB image
> 
> Sent 1 000 000 DGB with fee of 1.0 DGB/kB image
> 
> Attempted to send 1 000 000 DGB with fee of 2.0 DGB/kB, but failed due to TX fee being too large. TX fee would have been 149.2 DGB. image


--------------------------------------------------------------------------------------------------------

We cannot change the kB size. So if you have 75kb * 2dgb * 1.000.000 = 150dgb.
Then we need to change the 100 DGB/transaction limit. Don't think that is good.

You can easy send 75kb * 0.1dgb * 10.000.000 dgb =  75dgb

But i think with this kind of transactions use -maxtxfee ... if you wanna set a high fee.

**Comment by beggsdl** [comment]
That test of 1 000 000 at 2.0/kB was just to verify that it would fail when the fee was over the max.

**Comment by ghost** [comment]
> That test of 1 000 000 at 2.0/kB was just to verify that it would fail when the fee was over the max.

Sorry Tnx!!!!

**Review by ycagel — APPROVED** [review]
cACK. Glad to see the additional testing and update of this PR. Appreciate all the work. Will look to @JaredTate and @gto90 for their thoughts and review.

**Review by gto90 — APPROVED** [review]
utACK

**Comment by JaredTate** [comment]
This compiles & runs for me. My question is should this be even higher? If someone dedusts a few 1000 utxos, it could be a lot higher fee. We do not want to prevent that ability. What does everyone think?

If we look at BTC: 
`//! static const CAmount DEFAULT_TRANSACTION_MINFEE = 1000;`
https://github.com/bitcoin/bitcoin/blob/7b397025133cbc4c37be6cabc9e55b4c9a38f8ee/src/wallet/wallet.h#L110-L111
`//! constexpr CAmount DEFAULT_TRANSACTION_MAXFEE{COIN / 10};`
https://github.com/bitcoin/bitcoin/blob/7b397025133cbc4c37be6cabc9e55b4c9a38f8ee/src/wallet/wallet.h#L137-L138

**Comment by beggsdl** [comment]
> This compiles & runs for me. My question is should this be even higher? If someone dedusts a few 1000 utxos, it could be a lot higher fee. We do not want to prevent that ability. What does everyone think?


My problem when testing was that I was running into “transaction too large” before I was hitting the max tx fee. I got this when I would try to send a couple million DGB, mostly from Coinbase TXs. Could dedusting run into the same thing and not often hit the max tx fee?

**Comment by JaredTate** [comment]
> > This compiles & runs for me. My question is should this be even higher? If someone dedusts a few 1000 utxos, it could be a lot higher fee. We do not want to prevent that ability. What does everyone think?
> 
> My problem when testing was that I was running into “transaction too large” before I was hitting the max tx fee. I got this when I would try to send a couple million DGB, mostly from Coinbase TXs. Could dedusting run into the same thing and not often hit the max tx fee?

You were probably hitting the max size limit for a transaction to be. That's probably our answer for how high fees should be. We should hit the “transaction too large” before the fee to high error. If that's the case now then we are probably good with this.

The max size of a TX to relay/mine and source of "Transaction too large" error is `MAX_STANDARD_TX_WEIGHT` found here:
https://github.com/DigiByte-Core/digibyte/blob/3c77decac7242a97d255b5273f8207836b67ce9a/src/policy/policy.h#L26-L27

But these can also limit TX size:
https://github.com/DigiByte-Core/digibyte/blob/3c77decac7242a97d255b5273f8207836b67ce9a/src/policy/policy.h#L42-L51

The "Transaction too large" error is defined here, which is triggered by `MAX_STANDARD_TX_WEIGHT`:

https://github.com/DigiByte-Core/digibyte/blob/3c77decac7242a97d255b5273f8207836b67ce9a/src/wallet/spend.cpp#L840-L846

**Review by JaredTate — APPROVED** [review]
ACK. Thanks a ton for everyone's help on this!

**Comment by ghost** [comment]
> ACK. Thanks a ton for everyone's help on this!

@JaredTate Thank you for all the work you do for DigiByte!!

**Pull request merged**
