### PR TITLE
Use CSHA256 for groestl,qubit and skein,Add openssl to depends and fix sse2 config 

### PR DESCRIPTION
**Pull request by akshaynexus**

### CODE REVIEW

**Comment by ChillingSilence** [comment]
Unsure how related this is specifically to this pull request but I'm currently getting the following when I built from your 8.19.0 branch after syncing the headers to 100%:

> master@compiler:~$ ./digibyte/src/digibyte-cli getblockchaininfo
> error code: -1
> error message:
> rpc/blockchain.cpp:72 (GetDifficulty)
> Internal bug detected: 'blockindex'

**Comment by akshaynexus** [comment]
This seems to be a issue with the current branch itself

**Comment by ChillingSilence** [comment]
Looks good to me here, compiles now :)

**Comment by akshaynexus** [comment]
Can this be merged or anything else needed?

**Comment by ycagel** [comment]
Thank you for all your hard work Akshay! This has been merged.

**Pull request merged**
