### PR TITLE
WIP: Fix Functional Tests

### PR DESCRIPTION
**Pull request by JaredTate**
Starting draft PR for fixing & finalizing all functional tests. Right now we have 214 passing with 23 disabled ( not sure how many were also disabled in BTC for various reasons, or how many Yoshi commented out).

You can learn more about functional tests here: https://github.com/DigiByte-Core/digibyte/tree/feature/8.22.0/test

You can run all tests at once from the main digibyte directory after comping by running:

```
test/functional/test_runner.py --extended
```

Note you can --jobs=N to add more threads. It defaults to 4, yet trying anywhere from 2 - 8 you get random test failures because the previous test node is not spun down correctly. Yet when you run the failing test individually it will pass.

### CODE REVIEW

**Review by gto90 — APPROVED** [review]
ACK

Great work on this @JaredTate .  I will open two new issues to cover the functional test suite runner having trouble running all of the functional tests in a batch, and one for resolving the zmq functional test failure.

**Review by digicontributer — APPROVED** [review]
> and one for resolving the zmq functional test failure.

ACK for this in that case.

**Comment by gto90** [comment]
New issue raised for the functional test failures here: https://github.com/DigiByte-Core/digibyte/issues/95

**Comment by gto90** [comment]
New issue raised for the failing zmq functional test here: https://github.com/DigiByte-Core/digibyte/issues/96

**Comment by ycagel** [comment]
cACK

Great work @JaredTate.

**Review by ycagel — APPROVED** [review]

**Pull request merged**
