### PR TITLE
Fix wallet_abandonconflict.py Functional Tests

### PR DESCRIPTION
**Pull request by JaredTate**
This PR fixes  wallet_abandonconflict.py functional tests. 

To test this:

Compile:

```
  ./autogen.sh
  ./configure
  make -j 8
```
Run Specific Functional Tests
```
test/functional/test_runner.py wallet_abandonconflict.py
```
Screenshot 2024-03-19 at 3 31 15 PM

### CODE REVIEW

**Comment by ghost** [comment]
Test already work?
Screenshot from 2024-03-20 09-31-01
Screenshot from 2024-03-20 09-34-56

Test fixed in PR https://github.com/DigiByte-Core/digibyte/pull/190

**Comment by JaredTate** [comment]
This is very strange, the test was failing for me over and over yesterday for several hours until I made those changes. Let me clean and revert and see if it passes.

**Comment by ghost** [comment]
> This is very strange, the test was failing for me over and over yesterday for several hours until I made those changes. Let me clean and revert and see if it passes.

Yes sometimes if i do the test to fast. Some also fail for me.

**Comment by JaredTate** [comment]
> > This is very strange, the test was failing for me over and over yesterday for several hours until I made those changes. Let me clean and revert and see if it passes.
> 
> Yes sometimes if I do the test too fast. Some also fail for me.

I only run 1 job at a time. But I ran this individually... it failed numerous times till I made this PR. I don't understand what other change we made recently. Currently, with this PR, these are my remaining failures:

Screenshot 2024-03-19 at 8 14 14 PM

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
> > > This is very strange, the test was failing for me over and over yesterday for several hours until I made those changes. Let me clean and revert and see if it passes.
> > 
> > 
> > Yes sometimes if I do the test too fast. Some also fail for me.
> 
> I only run 1 job at a time. But I ran this individually... it failed numerous times till I made this PR. I don't understand what other change we made recently. Currently, with this PR, these are my remaining failures:
> 
> Screenshot 2024-03-19 at 8 14 14 PM

ACK Tested. Old and new test are working for me. @JaredTate

**Review by ycagel — APPROVED** [review]
cACK

**Review by gto90 — APPROVED** [review]
ACK

**Pull request merged**
