### PR TITLE
New mainnet & testnet seed server.

### PR DESCRIPTION
**Pull request by ghost**
New seed servers: 
**MAINNET** ( Netherlands ):  eu.digibyteseed.com ( 149.210.200.222 )
&&
**testnet** ( Finland ): testnet.digibyteseed.com ( 65.109.162.15 )

Jan de jong

### CODE REVIEW

**Comment by saltedlolly** [comment]
Tested OK:
https://www.whatsmydns.net/#A/eu.digibyteseed.com 
https://www.whatsmydns.net/#A/testnet.digibyteseed.com

**Review by saltedlolly — APPROVED** [review]
utACK

Thanks for running your seeders.

**Review by JaredTate — APPROVED** [review]
tACK

Looks good to me: https://www.whatsmydns.net/#A/eu.digibyteseed.com

Thank you!

**Review by ycagel — APPROVED** [review]
tACK. Great job!

**Review by saltedlolly — APPROVED** [review]
tACK

**Review by j50ng — APPROVED** [review]
tACK- looks good!  Great work!

**Pull request merged**
