### PR TITLE
Refactor Subsidy Code

### PR DESCRIPTION
**Pull request by SmartArray**
## Refactor Subsidy Code
Looking at the code in `validation.cpp`: https://github.com/DigiByte-Core/digibyte/blob/1cb4d6b7132961c7fabbb7362949655bb27acee9/src/validation.cpp#L1216-L1244 it is barely documented, has weird indentions and is hard to read.
The original Bitcoin Code-Style Convention was not followed at all.

This PR is supposed to tidy up the subsidy code before introducing future changes (see https://github.com/DigiByte-Core/digibyte/issues/20)

### Expectations
The altered code must still pass the `main_tests` unit test with 100%.

### Changes
https://github.com/DigiByte-Core/digibyte/commit/d54c650a2256726b72165cc310f41585469813ae merged `GetBlockSubsidy` and `GetDGBSubsidy` into one function. 
https://github.com/DigiByte-Core/digibyte/commit/24b4d2388ee6257955057d0215b5209c2e078be4 removes dead code that wasn't removed with the previous commit.

### How to verify?
0) Clone using
```bash
git clone https://github.com/SmartArray/digibyte.git -b refactor/subsidy && cd digibyte
```
1) Prepare the build environment
```bash
./autogen.sh && ./configure
```
2) Compile the test suite
```bash
cd src/test
make -j4
```
3) Run it using
```bash
./test_digibyte --run_test=main_tests
```

### Expected outcome
```
$ ./test_digibyte --run_test=main_tests
Running 2 test cases...
*** No errors detected
```

### CODE REVIEW

**Comment by ChillingSilence** [comment]
ACK, beautifully commented too! 👍 Thanks @SmartArray

**Comment by SmartArray** [comment]
> ACK, beautifully commented too! 👍 Thanks @SmartArray

Thank you @ChillingSilence. Documentation is the biggest intent of this PR.

Also, this PR is a great example of how development can continue on DigiByte Core now, since we have the working unit tests.

**Review by ChillingSilence — DISMISSED** [review]

**Review by gto90 — DISMISSED** [review]
utACK

**Comment by JaredTate** [comment]
Looks good initially. The automated tests are great. But to double check everything 100% was this tested with a running tweaked 7.17.2 node to sync from scratch on main net?

**Comment by ChillingSilence** [comment]
Yes that's what the unit tests confirm. They do a full subsidy simulation.
If we don't trust the unit tests then we need a proposal for further amendments to them so that they are considered 'trustworthy'

However yes, it syncs from scratch.

**Comment by SmartArray** [comment]
Thanks @JaredTate for reviewing https://github.com/DigiByte-Core/digibyte/pull/40

Thanks to you, this PR is currently being validated by the approved automatic CI workflow and it should yield the build status shortly.

**Review by gto90 — APPROVED** [review]
ACK

**Review by ChillingSilence — APPROVED** [review]

**Review by JaredTate — APPROVED** [review]
utACK

**Pull request merged**
