### PR TITLE
Replace Bitcoin static seeds with DigiByte static seeds

### PR DESCRIPTION
**Pull request by saltedlolly**
Bitcoin static seed nodes have been updated with the current list of full nodes from digibyteseed.com using the generate-seeds.py script here: https://github.com/DigiByte-Core/digibyte/blob/develop/contrib/seeds/README.md

(Note: I did not run the makeseeds.py script. Only generate-seeds.py. It might be good to update the former so it can automatically get the current seeds from digibyteseeds.com)

We may want to update this again before v8.22 is released. 

**IMPORTANT: We should definitely add some Tor nodes as well to better fortify the DigiByte network. There are currently none.**

### CODE REVIEW

**Comment by LeroyGerrits** [comment]
What is the actual use of this static list, though? Does it have a functional use in DigiByte's actual source? Aren't seeders used for this specific purpose?

I've been keeping track of digibyteseed.com for a while now (ever since I launched my first node) and from what I've seen the list varies greatly over time. The majority of people setting up a node don't keep it up for very long or run it from home and have an unstable/unreliable connection. By the time this PR will get reviewed, a big part of this list will be obsolete again.

**Comment by saltedlolly** [comment]
Obviously many of these nodes will not stay current. That said most of the included full nodes have been there since the start of digibyteseed.com - check the relatability score. 

The point is that (a) even a single IP to a working DigiByte Node is better than only having the current list of likely out of date Bitcoin Nodes, and (b) these are there to prevent a hypothetical situation where all the seeders go offline (perhaps someone trying to take down the network). They  act as a backup to ensure new nodes can always find another node to connect to.

This is also a first step. We really should add some Tor full nodes to this list identified by their onion address which should remain static even if their IP address changes. This makes it much harder for a bad actor to prevent new nodes from finding other nodes to connect to. Bitcoin has Tor nodes and i2p nodes, so should DigiByte. 

I have a plan to add Tor support to DigiNode Tools to make this easier. I hope to get to this in the new year.

**Review by JaredTate — APPROVED** [review]
cACK. Thanks for taking the time to do this. I don't see any issue with this. It helps with a new node syncing with the network. However, a lot of times I am not sure many of these ip's will stay on line very long. Testnet changes should help though.

**Review by gto90 — APPROVED** [review]
cACK.  Thank you @saltedlolly for updating these!

**Review by ycagel — APPROVED** [review]
cACK. Thanks for your efforts @saltedlolly!

**Pull request merged**
