### PR TITLE
Partial wallet_basic.py Fix & 5 other Functional Test Fixes

### PR DESCRIPTION
**Pull request by JaredTate**
This PR fixes 1 of 2 functional tests for wallet_basic.py and 5 other functional tests. This test wallet_basic.py  is a doozy and after spending a few hours on it I figured I would share what I have done so far to see if anyone else has suggestions.

To test this:

Compile:

```
  ./autogen.sh
  ./configure
  make -j 8
```
Run Specific Functional Tests
```
test/functional/test_runner.py wallet_basic.py
test/functional/test_runner.py interface_digibyte_cli.py mining_basic.py mempool_unbroadcast.py rpc_signrawtransaction.py wallet_importprunedfunds.py 
```
Screenshot 2024-03-08 at 9 37 22 AM

Screenshot 2024-03-08 at 10 07 21 AM

Screenshot 2024-03-08 at 11 32 13 AM

Screenshot 2024-03-08 at 8 52 16 AM

I am still stuck on this error for 2nd wallet_basic.py  test:

Screenshot 2024-03-08 at 8 52 09 AM

### CODE REVIEW

**Comment by JaredTate** [comment]
I won't push any more functional test fixes to this PR. Will keep it to 5 fixes per PR at a time.

**Comment by JaredTate** [comment]
After this PR I still have 39 failing tests. 
Screenshot 2024-03-08 at 11 33 08 AM

**Review by ghost — APPROVED** [review]
Nice work! @JaredTate 
Screenshot from 2024-03-08 19-51-21
Same here 39 test Failed.
ACK Tested

**Review by ycagel — APPROVED** [review]
cACK. Excellent work @Jongjan88 and @JaredTate!

**Review by gto90 — APPROVED** [review]
utACK

**Pull request merged**
