### PR TITLE
WIP: Refactor dandelion implementation

### PR DESCRIPTION
**Pull request by barrystyle**
Salvaged the existing implementation brought across from Digibyte 7.17.3

### CODE REVIEW

**Comment by JaredTate** [comment]
Good find Barry. I also agree splitting dandelion off to its own .cpp is a good move.

The client compiles for me without any issues, and after running it for an hour it does appear that horrid bug may be gone now. I need to run it for a few more hours to make sure. Surprisingly the client actually boots much faster for me after this PR.

However, there are 3 other issues with dandelion & tx/relay I think we still have. 

1st) We still have the issue where it appears the wallet is trying to submit every TX twice to mempool.

```
2021-11-01T15:53:12Z received: tx (191 bytes) peer=5
2021-11-01T15:53:12Z Enqueuing TransactionAddedToMempool: txid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad wtxid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad
2021-11-01T15:53:12Z Blockpolicy error mempool tx 98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad already being tracked
2021-11-01T15:53:12Z Enqueuing TransactionAddedToMempool: txid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad wtxid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad
2021-11-01T15:53:12Z TransactionAddedToMempool: txid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad wtxid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad
2021-11-01T15:53:12Z AcceptToMemoryPool: peer=5: accepted 98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad (poolsz 13 txn, 15 kB)
2021-11-01T15:53:12Z TransactionAddedToMempool: txid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad wtxid=98f383c24cc4b41c7bac7d596ae254a54987f611b6a55ce82ff3a28c943146ad
2021-11-01T15:53:13Z received: inv (37 bytes) peer=2
```
2nd: I still do not think it is embargoing dandelion txs properly. A lot of this I think is related to the issue we discussed here: https://github.com/DigiByte-Core/digibyte/issues/77

Mainly AcceptToMemoryPool and RelayWalletTransaction were combined to create SubmitMemoryPoolAndRelay.

I still think SubmitMemoryPoolAndRelay needs the embargo code like RelayWalletTransaction used to have. As that embargo code was in 2 places in the previous dandelion implementation.

3rd: I still don't think its possible to fully disable dandelion, nut sure if it actually ever was in 7.17. But that is also something else that should be added back to it.

I was working on this addition to SubmitMemoryPoolAndRelay, but it needs more work. Connman rework was causing issues:
```

if (!gArgs.GetBoolArg("-disabledandelion", DEFAULT_DISABLE_DANDELION)) {
        LogPrint(BCLog::DANDELION, "Relaying dandeliontx with no embargo time\n");
        std::chrono::microseconds current_time = GetTime<std::chrono::microseconds>();

        std::chrono::seconds nEmbargo = std::chrono::duration_cast<std::chrono::seconds>(DANDELION_EMBARGO_MINIMUM + PoissonNextSend(current_time, DANDELION_EMBARGO_AVG_ADD));

        connman->insertDandelionEmbargo(GetHash(), nEmbargo);

        LogPrint(BCLog::DANDELION,"dandeliontx %s embargoed for %d seconds\n", GetHash().ToString(),(nEmbargo - std::chrono::duration_cast<std::chrono::seconds>(current_time)).count());

        CInv inv(MSG_DANDELION_TX, GetHash());

        return connman->localDandelionDestinationPushInventory(inv.hash);
    }

```

**Comment by barrystyle** [comment]
1) The routine that submits to memory pool (once for m_mempool and once for m_stempool) will print the same function name each time its called (TransactionAddedToMempool from AcceptToMemoryPool).
2) There is a call missing to CheckDandelionEmbargoes(), just added it back in.
3) This is very similar to what i'd come up with in node/transaction.cpp - the difference between dandelion being enabled or disabled from a local node's point of view, is whether the local node places its own transactions in the embargo - or whether it just sends them as normal.

https://github.com/barrystyle/digibyte/commit/7b1ee1afd85c09fd2c866a3e73391f051cb859b1#diff-54409bbc1a072860afa5d3e2c920ac585b819f1db7ba0d894a4c64d7a66f8464R122-R137

**Comment by JaredTate** [comment]
So it appears bug is still there. Have reproduced it multiple times now, still crashes with the same error. As for entering mempool twice, still doesn't explain this error:

```
2021-11-03T18:28:57Z Blockpolicy error mempool tx 7e864dbf585a7621f1d276abaf8150b19b1f7dfd56e99149cbd0b5c90022aca1 already being tracked

```

Here is the bug LLDB backtrace:
```
(lldb) up
frame #1: 0x00000001012210c6 digibyted`SipHashUint256(k0=1681181663665396676, k1=9298080454276746492, val=0x0000000000000038) at siphash.cpp:97:22
   94  	uint64_t SipHashUint256(uint64_t k0, uint64_t k1, const uint256& val)
   95  	{
   96  	    /* Specialized implementation for efficiency */
-> 97  	    uint64_t d = val.GetUint64(0);
   98  	
   99  	    uint64_t v0 = 0x736f6d6570736575ULL ^ k0;
   100 	    uint64_t v1 = 0x646f72616e646f6dULL ^ k1;
(lldb) up
frame #2: 0x000000010090ede6 digibyted`SaltedTxidHasher::operator(this=0x000000010480d1a8, txid=0x0000000000000038)(uint256 const&) const at hasher.h:22:16
   19  	    SaltedTxidHasher();
   20  	
   21  	    size_t operator()(const uint256& txid) const {
-> 22  	        return SipHashUint256(k0, k1, txid);
   23  	    }
   24  	};
   25  	
(lldb) up
frame #3: 0x000000010054da60 digibyted`boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::__1::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::bucket_array<std::__1::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_unique_tag, boost::multi_index::detail::hashed_index_global_iterator_tag> boost::multi_index::detail::hashed_index<mempoolentry_txid, SaltedTxidHasher, std::__1::equal_to<uint256>, boost::multi_index::detail::nth_layer<1, CTxMemPoolEntry, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<mempoolentry_txid, SaltedTxidHasher, mpl_::na, mpl_::na>, boost::multi_index::hashed_unique<boost::multi_index::tag<index_by_wtxid, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, mempoolentry_wtxid, SaltedTxidHasher, mpl_::na>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<descendant_score, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByDescendantScore>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<entry_time, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByEntryTime>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByAncestorFee>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::__1::allocator<CTxMemPoolEntry> >, boost::mpl::vector0<mpl_::na>, boost::multi_index::detail::hashed_unique_tag>::find<uint256, SaltedTxidHasher, std::__1::equal_to<uint256> >(this=0x000000010480d150, k=0x0000000000000038, hash=0x000000010480d1a8, eq=0x000000010480d1b8, (null)=mpl_::false_ @ 0x000070000295e1b8) const at hashed_index.hpp:1605:38
   1602	    const CompatibleKey& k,
   1603	    const CompatibleHash& hash,const CompatiblePred& eq,mpl::false_)const
   1604	  {
-> 1605	    std::size_t buc=buckets.position(hash(k));
   1606	    for(node_impl_pointer x=buckets.at(buc)->prior();
   1607	        x!=node_impl_pointer(0);x=node_alg::next_to_inspect(x)){
   1608	      if(eq(k,key(index_node_type::from_impl(x)->value()))){
(lldb) up
frame #4: 0x000000010054d9cf digibyted`boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::__1::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::bucket_array<std::__1::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_unique_tag, boost::multi_index::detail::hashed_index_global_iterator_tag> boost::multi_index::detail::hashed_index<mempoolentry_txid, SaltedTxidHasher, std::__1::equal_to<uint256>, boost::multi_index::detail::nth_layer<1, CTxMemPoolEntry, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<mempoolentry_txid, SaltedTxidHasher, mpl_::na, mpl_::na>, boost::multi_index::hashed_unique<boost::multi_index::tag<index_by_wtxid, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, mempoolentry_wtxid, SaltedTxidHasher, mpl_::na>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<descendant_score, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByDescendantScore>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<entry_time, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByEntryTime>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByAncestorFee>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::__1::allocator<CTxMemPoolEntry> >, boost::mpl::vector0<mpl_::na>, boost::multi_index::detail::hashed_unique_tag>::find<uint256, SaltedTxidHasher, std::__1::equal_to<uint256> >(this=0x000000010480d150, k=0x0000000000000038, hash=0x000000010480d1a8, eq=0x000000010480d1b8) const at hashed_index.hpp:541:12
   538 	    const CompatibleKey& k,
   539 	    const CompatibleHash& hash,const CompatiblePred& eq)const
   540 	  {
-> 541 	    return find(
   542 	      k,hash,eq,promotes_1st_arg<CompatiblePred,CompatibleKey,key_type>());
   543 	  }
   544 	
(lldb) up
frame #5: 0x000000010054b9a1 digibyted`boost::multi_index::detail::hashed_index_iterator<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolEntry, std::__1::allocator<CTxMemPoolEntry> > > > > > >, boost::multi_index::detail::bucket_array<std::__1::allocator<CTxMemPoolEntry> >, boost::multi_index::detail::hashed_unique_tag, boost::multi_index::detail::hashed_index_global_iterator_tag> boost::multi_index::detail::hashed_index<mempoolentry_txid, SaltedTxidHasher, std::__1::equal_to<uint256>, boost::multi_index::detail::nth_layer<1, CTxMemPoolEntry, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<mempoolentry_txid, SaltedTxidHasher, mpl_::na, mpl_::na>, boost::multi_index::hashed_unique<boost::multi_index::tag<index_by_wtxid, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, mempoolentry_wtxid, SaltedTxidHasher, mpl_::na>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<descendant_score, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByDescendantScore>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<entry_time, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByEntryTime>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::identity<CTxMemPoolEntry>, CompareTxMemPoolEntryByAncestorFee>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::__1::allocator<CTxMemPoolEntry> >, boost::mpl::vector0<mpl_::na>, boost::multi_index::detail::hashed_unique_tag>::find<uint256>(this=0x000000010480d150, k=0x0000000000000038) const at hashed_index.hpp:531:12
   528 	  template<typename CompatibleKey>
   529 	  iterator find(const CompatibleKey& k)const
   530 	  {
-> 531 	    return find(k,hash_,eq_);
   532 	  }
   533 	
   534 	  template<
(lldb) up
frame #6: 0x0000000100853cc7 digibyted`CTxMemPool::GetIter(this=0x000000010480d0a0, txid=0x0000000000000038) const at txmempool.cpp:903:21
   900 	
   901 	std::optional<CTxMemPool::txiter> CTxMemPool::GetIter(const uint256& txid) const
   902 	{
-> 903 	    auto it = mapTx.find(txid);
   904 	    if (it != mapTx.end()) return it;
   905 	    return std::nullopt;
   906 	}
(lldb) up
frame #7: 0x000000010034d2cc digibyted`(anonymous namespace)::PeerManagerImpl::ProcessGetData(this=0x00000001048de5b0, pfrom=0x000000010581a200, peer=0x00000002e3dda608, interruptMsgProc=0x0000000105008bc8)::Peer&, std::__1::atomic<bool> const&) at net_processing.cpp:2006:41
   2003	            std::vector<uint256> parent_ids_to_add;
   2004	            {
   2005	                LOCK(m_mempool.cs);
-> 2006	                auto txiter = m_mempool.GetIter(tx->GetHash());
   2007	                if (txiter) {
   2008	                    const CTxMemPoolEntry::Parents& parents = (*txiter)->GetMemPoolParentsConst();
   2009	                    parent_ids_to_add.reserve(parents.size());
(lldb) up
frame #8: 0x00000001002eb765 digibyted`(anonymous namespace)::PeerManagerImpl::ProcessMessage(this=0x00000001048de5b0, pfrom=0x000000010581a200, msg_type="getdata", vRecv=0x00000002cad658c0, time_received=(__rep_ = 1635964146271186), interruptMsgProc=0x0000000105008bc8) at net_processing.cpp:3074:13
   3071	        {
   3072	            LOCK(peer->m_getdata_requests_mutex);
   3073	            peer->m_getdata_requests.insert(peer->m_getdata_requests.end(), vInv.begin(), vInv.end());
-> 3074	            ProcessGetData(pfrom, *peer, interruptMsgProc);
   3075	        }
   3076	
   3077	        return;
(lldb) up
frame #9: 0x00000001002f6460 digibyted`(anonymous namespace)::PeerManagerImpl::ProcessMessages(this=0x00000001048de5b0, pfrom=0x000000010581a200, interruptMsgProc=0x0000000105008bc8) at net_processing.cpp:4234:9
   4231	    unsigned int nMessageSize = msg.m_message_size;
   4232	
   4233	    try {
-> 4234	        ProcessMessage(*pfrom, msg_type, msg.m_recv, msg.m_time, interruptMsgProc);
   4235	        if (interruptMsgProc) return false;
   4236	        {
   4237	            LOCK(peer->m_getdata_requests_mutex);
(lldb) up
frame #10: 0x00000001002fbd50 digibyted`non-virtual thunk to (anonymous namespace)::PeerManagerImpl::ProcessMessages(CNode*, std::__1::atomic<bool>&) at net_processing.cpp:0
   1   	// Copyright (c) 2009-2010 Satoshi Nakamoto
   2   	// Copyright (c) 2009-2020 The Bitcoin Core developers
   3   	// Copyright (c) 2014-2020 The DigiByte Core developers
   4   	// Distributed under the MIT software license, see the accompanying
   5   	// file COPYING or http://www.opensource.org/licenses/mit-license.php.
   6   	
   7   	#include <net_processing.h>
(lldb) cs

```

As for the embargo code, in the 7.17.3 implementation it was in there twice. I think once as a relay point, once as an origination embargo point.

**Comment by JaredTate** [comment]
So by reverting ProcessGetData to be same as the BTC v22 function the client works fine. So for sure the bug is in ProcessGetData. Its helpful to take a look at a diff check between BTC v22 and our 8.22: https://www.diffchecker.com/nqczYSQx

I still think SubmitMemoryPoolAndRelay needs reworked further as well.

**Comment by JaredTate** [comment]
Should we close this PR and reapply dandelion to the new: https://github.com/DigiByte-Core/digibyte/tree/feature/8.22dandelion

**Pull request closed without merging**
