### PR TITLE
Fix 2 wallet_groups.py Functional Tests

### PR DESCRIPTION
**Pull request by JaredTate**
This PR fixes 2 wallet_groups.py functional tests. 

To test this:

Compile:

```
  ./autogen.sh
  ./configure
  make -j 8
```
Run Specific Functional Tests
```
test/functional/test_runner.py wallet_groups.py 
```
Screenshot 2024-03-20 at 5 09 38 PM

### CODE REVIEW

**Review by ghost — APPROVED** [review]
ACK Tested

**Comment by ghost** [comment]
Screenshot from 2024-03-21 11-40-08

**Review by ycagel — APPROVED** [review]
cACK

**Review by gto90 — APPROVED** [review]
ACK

**Pull request merged**
